artists_data = {
'Cecilia Stalin': 'United Kingdom',
    'Eject': 'Germany',
    'Excess Pressure': 'Germany',
    'Fathers of Sound': 'Italy',
    'Jean‐Claude Malgoire': 'France',
    'Lee Abraham': 'United Kingdom',
    'Lonesome Echo Production': 'Japan',
    'Lê Cát Trọng Lý': 'Vietnam',
    'Mydo': 'Sweden',
    'Mitra Kaislaranta': 'Finland',
    'Oldschool Union': 'Finland',
    'Peter Coyle': 'United Kingdom',
    'Raoul Casadei': 'Italy',
    'Ryan Toby': 'United States',
    'Shaden': 'Indonesia',
    'Song Sung': 'Ireland',
    'The Barbarellas': 'Norway',
    'The Relationship': 'United States',
    'TPS': 'Poland',
    'Vittorio De Sica': 'Italy',
    'ХАХАХА': 'Macedonia',
    'たいらいさお': 'Japan',
    'Ardijah': 'New Zealand',
    'Awaken The Echoes': 'United States',
    'Bastard Bearded Irishmen': 'United States',
    'Belfegor': 'Poland',
    'Biscuit': 'United States',
    'Chackie Jam': 'Belgium',
    'Cheeky Parade': 'Japan',
    'Claude‐Joseph Rouget de l’Isle': 'France',
    'Danny Hutton': 'Ireland',
    'Def Räädu': 'Estonia',
    'El Ritual': 'Mexico',
    'Epoxy': 'Sweden',
    'Eskuche': 'United States',
    'Fanon Flowers': 'United States',
    'God Body Disconnect': 'United States',
    'Ink Midget': 'Slovakia',
    'Jozef Zsapka': 'Slovakia',
    'Kelly Simonz’s Blind Faith': 'Japan',
    'Mitomi Tokoto': 'Japan',
    'Raffaele Attanasio': 'Italy',
    'Ro-d-ys': 'Netherlands',
    'Satans Penguins': 'Sweden',
    'Seasick': 'United States',
    'Seduce The Heaven': 'Greece',
    'Stark Raving Mad': 'United States',
    'TIGERBERRY': 'Russia',
    'Trevor Wishart': 'United Kingdom',
    'UNDER THE COUNTER': 'Japan',
    '風雅なおと': 'Japan',
    '정진운': 'South Korea',
    'Basta!': 'Italy',
    'Black Coffey': 'United States',
    'CBC': 'Vietnam',
    'Cathedral Pearls': 'United States',
    'Ersay Üner': 'Turkey',
    'Getsix': 'United States',
    'Goodbye Heart': 'United States',
    'Green & Wood': 'United States',
    'H‐Kayne': 'Morocco',
    'KSK': 'Japan',
    'Mercenaries': 'United States',
    'Miroslav Donutil': 'Czech Republic',
    'Otto Virgial': 'United States',
    'Sliver': 'Austria',
    'Snowy': 'United Kingdom',
    'Third Wave': 'United Kingdom',
    'Tomika': 'Germany',
    'Bushbaby': 'United Kingdom',
    'Christine Salem': 'France',
    'Danny & The Islanders': 'Finland',
    'Death in Venice': 'Italy',
    'Der Moderne Man': 'Germany',
    'Despite Exile': 'Italy',
    'Edin‐Ådahl': 'Sweden',
    'Invierno': 'Chile',
    'Jerrold Immel': 'United States',
    'Koalacaust': 'United States',
    'Krvavy': 'Poland',
    'LugRadio': 'United Kingdom',
    'No Recess': 'Belgium',
    'PEACHBLACK': 'United States',
    'Pantxoa eta Peio': 'Spain',
    'Schola Hungarica': 'Hungary',
    'Sectorial': 'Ukraine',
    'Sully Sefil': 'France',
    'Third World War': 'United Kingdom',
    'Trevor Deep Jr.': 'Finland',
    'Tuff Jam': 'United Kingdom',
    'Veda Simpson': 'United States',
    'Yelo Molo': 'Canada',
    'Everlong': 'Indonesia',
    'Artan Lili': 'Serbia',
    'Beto': 'Turkey',
    'Cageless Birds': 'United States',
    'Crashpoint': 'Czech Republic',
    'Crimson Butterfly': 'Russia',
    'Eugène Bozza': 'France',
    'Frank Goosen': 'Germany',
    'HAP': 'United States',
    'Hermine': 'France',
    'Hostile Intent': 'United States',
    'Interstate Blues': 'United States',
    'Iran Costa': 'Brazil',
    'Johannes Moser': 'Germany',
    'Ketama126': 'Italy',
    'Krakow Kasanovas': 'Sweden',
    'Les Variations': 'France',
    'Mel Parsons': 'New Zealand',
    'Nadia Struiwigh': 'Netherlands',
    'Piskie Sits': 'United Kingdom',
    'Prouza': 'Czech Republic',
    'Roque Valero': 'Venezuela',
    'Soulitude': 'Germany',
    'Splatterheads': 'Australia',
    'Stoll Vaughan': 'United States',
    'The John Alldis Choir': 'United Kingdom',
    'The Sands': 'Belgium',
    'Valiant Swart': 'South Africa',
    '中原理恵': 'Japan',
    '王馨平': 'China',
    '인순이': 'South Korea',
    'Chris Breemer': 'Netherlands',
    'Concord String Quartet': 'United States',
    'Denea': 'Spain',
    'Drastik': 'United States',
    'Duress': 'United States',
    'Fabienne Louves': 'Switzerland',
    'Guy Cuevas': 'Cuba',
    'Jorma Kääriäinen': 'Finland',
    'JääBoiler': 'Estonia',
    'Karl-Heinz Schäfer': 'Germany',
    'Matthew Kyle': 'United States',
    'mochA': 'Japan',
    'Rodrigo Mercado': 'Spain',
    'ScotDrakula': 'Australia',
    'Sonitus Eco': 'Malta',
    'The B-Boys': 'United States',
    'Within Reach': 'Sweden',
    'Ритуальные Услуги': 'Russia',
    'Anla Courtis': 'Argentina',
    'Distant Echoes': 'Germany',
    'Downswing': 'United States',
    'Drunkard': 'Australia',
    'Éric Morena': 'France',
    'Event Cloak': 'Canada',
    'Flying Donuts': 'France',
    'Fruchtmax': 'Germany',
    'Inferia': 'Finland',
    'Magic Wave': 'Germany',
    'Mamukueno': 'Angola',
    'Purulent Spermcanal': 'Czech Republic',
    'Ryan Ellis': 'United Kingdom',
    'STÜBA Philharmonie': 'Germany',
    'Seduce': 'United States',
    'Sharon Scott': 'United States',
    'Space One': 'Italy',
    'The Super Orchestra': 'Sweden',
    'Amadea': 'Hungary',
    'Ambrozijn': 'Belgium',
    'Betong Hysteria': 'Norway',
    'Bocuma': 'Ireland',
    'Boyd Raeburn': 'United States',
    'Cashma Hoody': 'Germany',
    'Claustrophobia': 'China',
    'Cut Teeth': 'United States',
    'DJ Simi': 'Italy',
    'DJ Skeet Skeet': 'United States',
    'Fred Coury': 'United States',
    'Greasy Cafe': 'Thailand',
    'Jazz+Az': 'Hungary',
    'Krist Novoselic': 'United States',
    'Lindo Man': 'United Kingdom',
    'Michelle McAdorey': 'Canada',
    'Pepe Johansson': 'Finland',
    'Purna Das Baul': 'India',
    'Robert Craft': 'United States',
    'Steward': 'United Kingdom',
    'Aki ja Turo': 'Finland',
    'Fear of Lipstick': 'Canada',
    'James Primate': 'United States',
    'Jamie Bissmire': 'United Kingdom',
    'Leticia Sabater': 'Spain',
    'Lolita Scorned': 'Russia',
    'Ottilie Patterson': 'United Kingdom',
    'Oxygenfad': 'Canada',
    'Philippe de Monte': 'Belgium',
    'Prime Mover': 'Finland',
    'Psywarfare': 'United States',
    'Rasputin': 'United States',
    'Sonia Calico': 'Taiwan',
    'Staisha': 'Russia',
    'The Sunny Cowgirls': 'Australia',
    'Tommy Rehn': 'Sweden',
    'Under a Dying Sun': 'United States',
    'Burning Black': 'Italy',
    'Claire Guyot': 'France',
    'DJ Vortex & Arpa’s Dream': 'Italy',
    'Doc Hopper': 'United States',
    'Error Operator': 'United Kingdom',
    'Gasmask': 'Japan',
    'Jaroslav Uhlíř': 'Czech Republic',
    'Joseph Suchy': 'Germany',
    'Justin Burnett': 'United States',
    'Loic Penillo': 'France',
    'Martin Hannett': 'United Kingdom',
    'Mentenguerra': 'Spain',
    'Mondo Topless': 'United States',
    'Peel Dream Magazine': 'United States',
    'Pretty Wild': 'Sweden',
    'Rank Sinatra': 'Australia',
    'Safety': 'United States',
    'The Blue Bloods': 'United States',
    'White Circle Crime Club': 'Belgium',
    'Your Kid Sister': 'United States',
    'Zablujena generacija': 'Slovenia',
    'МСК': 'Russia',
    'Dead Beyond Buried': 'United Kingdom',
    'Debby van Dooren': 'Germany',
    'Eric Mercury': 'Canada',
    'Fisherman': 'France',
    'Follow the Train': 'United States',
    'Forever Lost': 'Norway',
    'Johnny Astro': 'United Kingdom',
    'KanibaL HolokausT': 'Serbia',
    'Leeches of Lore': 'United States',
    'Lori Andrews': 'United States',
    'Paragon of Beauty': 'Germany',
    'SkaЧай': 'Russia',
    'Tenebris': 'Poland',
    'The Candy Snatchers': 'United States',
    'Włodek Pawlik': 'Poland',
    'Oh Ye Denver Birds': 'Australia',
    'Ära Krâ': 'Germany',
    'Чиста Криниця': 'Ukraine',
    'Catherine Delaunay': 'France',
    'Cedric Myton': 'Jamaica',
    'Despise': 'Czech Republic',
    'Dotama': 'Japan',
    'Famous Eno': 'United Kingdom',
    'Groove Connektion': 'United Kingdom',
    'Guillaume Apollinaire': 'France',
    'Imaginary Friends': 'United States',
    'James Kelly': 'United States',
    'Kim Criswell': 'United States',
    'London Philharmonic Orchestra Wind Ensemble': 'United Kingdom',
    'Lyanno': 'United States',
    'MANNISH BOYS': 'Japan',
    "Mills' Ten Black Berries": 'United States',
    'Modern Error': 'United Kingdom',
    'Name in Lights': 'Sweden',
    'Patti Cathcart': 'United States',
    'Randy Jackson': 'United States',
    'Raxtor': 'Italy',
    'Right Direction': 'Netherlands',
    'Sanna Carlstedt': 'Sweden',
    'Stephen Dale Petit': 'United Kingdom',
    'Tabaré Cardozo': 'Uruguay',
    'Teacha Dee': 'Jamaica',
    'The Black Sunn': 'United States',
    'The Sexmachines': 'Switzerland',
    'Trevor Ashley': 'Australia',
    'Walter Schnitzelsson': 'Slovakia',
    'uBEAT': 'South Korea',
    'Arka': 'Latvia',
    'Domination Black': 'Finland',
    'Enoid': 'Switzerland',
    'Foster and Lloyd': 'United States',
    'Johanna Grüssner': 'Finland',
    'John Huijbers': 'Netherlands',
    'King Salami and The Cumberland Three': 'United Kingdom',
    'Krema Kawa': 'Belgium',
    'Leck': 'France',
    'Leroy “Horsemouth” Wallace': 'Jamaica',
    'Marie-Catherine Girod': 'France',
    'Marius Ziska': 'Faroe Islands',
    'Melhem Barakat': 'Lebanon',
    'Moreno + 2': 'Brazil',
    'Piezo': 'Canada',
    'Ron Anthony': 'United States',
    'Thalarion': 'Slovakia',
    '星勝': 'Japan',
    'Colossa': 'Netherlands',
    'David Carroll': 'United States',
    'Donovan Leitch': 'United States',
    'Gekko': 'Switzerland',
    'Giaches de Wert': 'Belgium',
    'Hardy Nilsson': 'Sweden',
    'Harv': 'Sweden',
    'ItsNate': 'United Kingdom',
    'John Hollenbeck': 'United States',
    'Kenneth Higney': 'United States',
    'Koolade': 'Croatia',
    'Laibert': 'Italy',
    'Moker': 'Belgium',
    "Rockin' Horse": 'Finland',
    'Rodrigo Santos': 'Brazil',
    'Shannon Mercer': 'Canada',
    'Stone Coal White': 'United States',
    'TAM TAM': 'Japan',
    'The Butchers': 'United States',
    '沼倉愛美': 'Japan',
    'About Wayne': 'Italy',
    'EUTHANASIE': 'Japan',
    'Enoq': 'Germany',
    'Etherdust': 'India',
    'Greg Reitan': 'United States',
    'Jon Cougar Concentration Camp': 'United States',
    'MANRAZE': 'United Kingdom',
    'Michael Mantra': 'United States',
    'Neil Armstrong': 'United States',
    'Ronn Matlock': 'United States',
    'Runaway Kids': 'United States',
    'Slowburn': 'Canada',
    'Soft Riot': 'United Kingdom',
    'Sons of Crom': 'Sweden',
    'The Gates of Eden': 'United States',
    'Vulcain': 'France',
    'Afeni Shakur': 'United States',
    'Alexander Koning': 'Netherlands',
    'BanDemonic': 'Greece',
    'Black Stalin': 'Trinidad and Tobago',
    'Duncan Chisholm': 'United Kingdom',
    'Ειρήνη Σκυλακάκη': 'Greece',
    'Keko Yunge': 'Chile',
    'Les Adams': 'United States',
    'Los Viejos': 'Mexico',
    'Metal Man': 'Canada',
    'Noize Draft': 'Russia',
    'PG2': 'Spain',
    'Proxies': 'Greece',
    'Suddenly, Tammy!': 'United States',
    'Tribes of Caïn': 'Switzerland',
    '40 Sons': 'Canada',
    'A Lion Named Roar': 'United States',
    'Bright Primate': 'United States',
    'Chewingum': 'Italy',
    'DJ Force': 'Australia',
    'Elio': 'Italy',
    'Fernando Costa': 'Brazil',
    'Giovanni Antonini': 'Italy',
    'H. Scott Salinas': 'United States',
    'J Frequency': 'Germany',
    'Kevin Conneff': 'Ireland',
    'Laura Critchley': 'United Kingdom',
    'Lola Dutronic': 'Canada',
    'Maria Bachmann': 'United States',
    'Maya Law': 'United Kingdom',
    'NGO': 'Japan',
    'Near Death Condition': 'Switzerland',
    'Nostramus': 'United Kingdom',
    'Nouveaunoise': 'Ireland',
    'Petra Glynt': 'Canada',
    'Pina Chulada': 'United States',
    'The Flipsides': 'United States',
    'The Loop Orchestra': 'Australia',
    'Vivien Savage': 'France',
    'White Tiger': 'United States',
    'Yall So Stupid': 'United States',
    'Zalabim': 'Sweden',
    '3rd Room': 'Italy',
    'A.A. Gray': 'United States',
    'Alina Hardin': 'United States',
    'Chris Carrabba': 'United States',
    'Christian Olivier': 'France',
    'Doll Factory': 'United States',
    'Donnacha Dennehy': 'Ireland',
    'Ernie Englund': 'Sweden',
    'Excretion': 'United States',
    'FØNX': 'United Kingdom',
    'Garnet Rogers': 'Canada',
    'Graveyard Dirt': 'Ireland',
    'Hablan por la Espalda': 'Uruguay',
    'Hamilton Cheifetz': 'United States',
    'IG Culture': 'United Kingdom',
    'Impure': 'Spain',
    'Ivan Roudyk': 'Russia',
    'Javi Punga': 'Argentina',
    'Kelly Pardekooper': 'United States',
    'Lizar': 'Poland',
    'Maarten Hercules': 'Netherlands',
    'Matt Whitehead': 'United Kingdom',
    'Maika': 'Japan',
    'Maika P.': 'France',
    'Michelle Amador': 'United States',
    'Nemos': 'Estonia',
    'New Moscow Symphony Orchestra': 'Russia',
    'Nuojuva': 'Finland',
    'Phil Pritchett': 'United States',
    'The Starlite Orchestra & Singers': 'Canada',
    'やまだ豊': 'Japan',
    'オワタP': 'Japan',
    'Andru Bemis': 'United States',
    'Armenta': 'Italy',
    'Careless Juja': 'United States',
    'Digital Dance': 'Belgium',
    'Exile Parade': 'United Kingdom',
    'Farmer Jason': 'United States',
    'Freddie Chavez': 'United States',
    'Jannah Beth': 'Australia',
    'Jonde': 'Finland',
    'Jump Back Jake': 'United States',
    'Kromozone': 'Netherlands',
    'LMan': 'Germany',
    'MrNorth': 'Ireland',
    'Matelo Ferret': 'France',
    'Milan Lasica': 'Slovakia',
    'Ockham’s Razor': 'United States',
    'OD': 'United Kingdom',
    'Philip Cortez': 'Belgium',
    'Sláinte': 'United States',
    'Sympuls-E': 'Russia',
    'Tasaday': 'Italy',
    'The Growler': 'Trinidad and Tobago',
    'The Vectors': 'United States',
    'Toby Martin': 'Australia',
    'Ulpu': 'Finland',
    'Арсений Креститель': 'Russia',
    'コツキミヤ': 'Japan',
    'Andrzej Garczarek': 'Poland',
    'Averi': 'United States',
    'Bionix': 'France',
    'Confusions': 'India',
    'Daimi': 'Denmark',
    'E.C. Illa': 'United States',
    'Eros Necropsique': 'France',
    'Faith or Fear': 'United States',
    'Friedrich Schiller': 'Germany',
    'Hex Machine': 'United States',
    'Isaac Russell': 'United States',
    'Marco Mzee': 'Austria',
    'Mark Steel': 'United Kingdom',
    'Murat Kilic': 'Australia',
    'Nutshell': 'Poland',
    'Satan Jokers': 'France',
    'Seger Ellis': 'United States',
    'Senne Guns': 'Belgium',
    'Steve Martland': 'United Kingdom',
    'Sunbear': 'Canada',
    'TURBOBIER': 'Austria',
    'William Brooks': 'United States',
    '五条下位': 'Japan',
    '2HD': 'Venezuela',
    'Adam Santoya': 'United States',
    'Alan Kelly': 'Ireland',
    'Annie Clark': 'United States',
    'Bad Business': 'United States',
    'Black Art': 'Russia',
    'Bob Bennett': 'United States',
    'Crushed Out': 'United States',
    'Dublin Aunts': 'Australia',
    'Ed Dowie': 'United Kingdom',
    'Father Funk': 'United Kingdom',
    'Francis Pilkington': 'United Kingdom',
    'Kago': 'Estonia',
    'Les Sauterelles': 'Switzerland',
    'P.K.O.': 'United States',
    'Raymond Devos': 'France',
    'Riccardo Broschi': 'Italy',
    'Sammy Salminen': 'Finland',
    'Scialpi': 'Italy',
    'Sopor': 'Russia',
    'Starjets': 'United Kingdom',
    'Sulo Saarits': 'Finland',
    'The Caravan': 'Canada',
    'Urban Sound Gallery': 'United States',
    'Мразь': 'Russia',
    '伍思凱': 'Taiwan',
    '小曽根真': 'Japan',
    'Annthennath': 'France',
    'Blackboard Jungle': 'United States',
    'Capture the Flag': 'United States',
    'Dresden & Johnston': 'United States',
    'Edward Oberon': 'United Kingdom',
    'Kriso': 'Finland',
    'Luca Lombardi': 'Italy',
    'Mairi MacInnes': 'United Kingdom',
    'Menahem Pressler': 'Germany',
    'Ozonna': 'United Kingdom',
    'Pia Colombo': 'France',
    'The Alexander Brothers': 'United Kingdom',
    'The Casual Terrorist': 'United Kingdom',
    'The McClain Sisters': 'United States',
    'William Masselos': 'United States',
    'BXRBER': 'United Kingdom',
    'Christian Gaubert': 'France',
    'DJ Nobunaga': 'Netherlands',
    'Даша Шульц': 'Russia',
    'Distress of Ruin': 'Finland',
    'Dreams in Static': 'United States',
    'Hereä': 'Finland',
    'Leander Kills': 'Hungary',
    'Maggot Colony': 'Taiwan',
    'Marie Luise Nikuta': 'Germany',
    'Paul Kwitek': 'Poland',
    'Salaliitto': 'Finland',
    'Sepulcher': 'Norway',
    'Skyloops': 'Argentina',
    'Tobi Vail': 'United States',
    'Ariane Blank': 'Germany',
    'Barbaro': 'Hungary',
    'CMC & Silenta': 'Germany',
    'Cherry Choke': 'United Kingdom',
    'Christopher Henderson': 'United States',
    'Coste Apetrea': 'Sweden',
    'Daytoner': 'United Kingdom',
    'Echo and The Empress': 'Australia',
    'Falling Leaves': 'Jordan',
    'High the Moon': 'Netherlands',
    'John Steinbeck': 'United States',
    'Kid Sole': 'Russia',
    'Las Armas Bs. As.': 'Argentina',
    'Marina City': 'United States',
    'Melchor de Marchena': 'Spain',
    'Oitão': 'Brazil',
    'Simplyd4rk': 'France',
    'Spiraling': 'United States',
    'Stone & Charden': 'France',
    'The A.X.E. Project': 'Bulgaria',
    'The Channel': 'United States',
    'The Maroons': 'United States',
    'The Rolling Creekdippers': 'United States',
    'When Bitter Spring Sleeps': 'United States',
    '林欣彤': 'China',
    'Acoustic Guitars': 'Denmark',
    'Antonin Artaud': 'France',
    'Book of Sand': 'United States',
    'Charles Gudagafva': 'Sweden',
    'Dead Neanderthals': 'Netherlands',
    'Derek Charke': 'Canada',
    'Firman': 'Indonesia',
    'Leo Grünbaum': 'Argentina',
    'Men of North Country': 'Israel',
    'Moral Dilemma': 'United Kingdom',
    'Noctifer': 'Italy',
    'Poko Cox': 'Russia',
    'Reek': 'Spain',
    'Robert Hurst': 'United States',
    'Roller Sis': 'Romania',
    'Sweetmates': 'United Kingdom',
    'The Go Faster Nuns': 'Germany',
    'Wolfsangel': 'Russia',
    'Zoe Rahman': 'United Kingdom',
    'eXiled': 'United Kingdom',
    'Živo Blato': 'Croatia',
    'Allies for Everyone': 'United States',
    'Alvin Stoller': 'United States',
    'Angrej Ali': 'India',
    'Bako': 'France',
    'Infestum': 'Belarus',
    'Irena Kwiatkowska': 'Poland',
    'Jonathan Kane': 'United States',
    'Jóvenes Pordioseros': 'Argentina',
    'Kari Vepsä': 'Finland',
    'Keith & Supabeatz': 'Italy',
    'Lo Village': 'United States',
    'Mark Archer': 'United Kingdom',
    'massendefeCt': 'Germany',
    'Małe Instrumenty': 'Poland',
    'Monkeybusiness': 'Denmark',
    'No-Big-Silence': 'Estonia',
    'Osewoudt': 'Netherlands',
    'Oxidelic': 'Bulgaria',
    'Pesky Gee!': 'United Kingdom',
    'Queen Sarah Saturday': 'United States',
    'Ropoporose': 'France',
    'Soliloquium': 'Sweden',
    'Stan Lee Cole': 'Belgium',
    'Thayer Sarrano': 'United States',
    'The Book of Lists': 'Canada',
    'Xtatik': 'Trinidad and Tobago',
    'Impurfekt': 'United States',
    'poloniumcubes': 'Russia',
    'Artists United Against Apartheid': 'United States',
    'Bülent Arel': 'Turkey',
    'Deep Winter': 'Russia',
    'Esperi': 'United Kingdom',
    'FouKi': 'Canada',
    'Jacob Moon': 'Canada',
    'Jo Vally': 'Belgium',
    'Lethargy of Death': 'Chile',
    'MiraculuM': 'Hungary',
    'Norman Zube': 'Germany',
    'Propane': 'Australia',
    'Sara Lee': 'United Kingdom',
    'Seven Steps to The Green Door': 'Germany',
    'The Low Budgets': 'United States',
    'The Parlour Trick': 'United States',
    'Yentl en de Boer': 'Netherlands',
    'koyori': 'Japan',
    '45 Degree Woman': 'Finland',
    'Angus Young': 'Australia',
    'Basa Basa Soundz': 'Ghana',
    'Bilders': 'New Zealand',
    'CLI-MAX S.': 'Japan',
    'Claudio Bisio': 'Italy',
    'Cyanide Pills': 'United Kingdom',
    'DJ Yuri Martins': 'Brazil',
    'Dana Immanuel': 'United Kingdom',
    'Elizabeth Kenny': 'United Kingdom',
    'Island Fox': 'United Kingdom',
    'Jean-Luc Godard': 'France',
    'Joe Luciano': 'Spain',
    'Poul Reichhardt': 'Denmark',
    'Pro Memoria': 'France',
    'Sasha Grey': 'United States',
    'Sorja Morja': 'Poland',
    'Super Junky Monkey': 'Japan',
    'Tatiana Troyanos': 'United States',
    'Terra Incognita': 'United States',
    'The Connection': 'United States',
    'The Cunts': 'United Kingdom',
    'a2c': 'Japan',
    'Александр Блок': 'Russia',
    'Лидия Русланова': 'Soviet Union',
    'НИИ Gulag': 'Russia',
    'あず♪': 'Japan',
    'Bandulu Dub': 'Portugal',
    'Blimp': 'Australia',
    'Change of Heart': 'United Kingdom',
    'Chorovaya Akademia': 'Russia',
    'Down My Throat': 'Finland',
    'Eran James': 'Australia',
    'Ethereal Pandemonium': 'Slovakia',
    'Fabiana': 'Italy',
    'Heinrich Mueller': 'United States',
    'Irma Agiashvili': 'Finland',
    'Jenny Hoyston': 'United States',
    'MDP': 'Ukraine',
    'Micky y Los Tonys': 'Spain',
    'Piyush Mishra': 'India',
    'Robert Llewellyn': 'United States',
    'Ryan Driver': 'Canada',
    'Serberus': 'United States',
    'Sid Hemphill': 'United States',
    'Sun in Aquarius': 'Australia',
    '산울림': 'South Korea',
    'Abdallah Ag Oumbadougou': 'Niger',
    'Bill Loko': 'Cameroon',
    'Brotherhood Creed': 'United States',
    'Devo Spice': 'United States',
    'Heliogabale': 'France',
    'Infera Bruo': 'United States',
    'Innerspace': 'Canada',
    'Jan Garber': 'United States',
    'Josh Parkinson': 'United Kingdom',
    '林芯儀': 'Taiwan',
    'Los Belmonts': 'Mexico',
    'Nisar Bazmi': 'Pakistan',
    'Roy Nathanson': 'United States',
    'Sister Cristina': 'Italy',
    'SLEAZE': 'United Kingdom',
    'TaiMO': 'Germany',
    'The New Creation': 'Canada',
    'Avalona': 'Germany',
    'Barbarian On The Groove': 'Japan',
    'DSKO': 'United States',
    'Daniel and the Lion': 'United States',
    'Dear Prudence': 'United Kingdom',
    'James Copeland': 'South Africa',
    'Jochem van Gelder': 'Netherlands',
    'John Barnes': 'United Kingdom',
    'Leo Reisman': 'United States',
    'Lil Silvio & El Vega': 'Colombia',
    'Psychic Blood': 'United States',
    'Samian': 'Canada',
    'Spooky & Sue': 'Netherlands',
    'Systek': 'United States',
    'The Fourth Way': 'United States',
    'The Oracle': 'United States',
    'Vox Clamantis': 'Estonia',
    'Wally Richardson': 'United States',
    'Wolfen': 'Germany',
    'Шелест Запахов': 'Ukraine',
    '初恋の嵐': 'Japan',
    'A Ghost of Flare': 'Japan',
    'Abnormyndeffect': 'Moldova',
    'Any Color Black': 'United Kingdom',
    'Benjamin Schmid': 'Austria',
    'Billy the Kill': 'Belgium',
    'Carmen Dragon': 'United States',
    'شاب صحراوي': 'Algeria',
    'DJ Pooh': 'United States',
    'José Peña Suazo y La Banda Gorda': 'Dominican Republic',
    'Kaya Jones': 'United States',
    'Le stelle di Mario Schifano': 'Italy',
    'Lodos': 'Turkey',
    'Married in Berdichev': 'United States',
    'Maz': 'Canada',
    'Mia Permanto': 'Finland',
    'Mick Jones': 'United Kingdom',
    'Minorstep': 'Greece',
    'Romane Serda': 'France',
    'Shelita Burke': 'United States',
    'Sickbag': 'France',
    'Static Blue': 'France',
    'Taavi Tulev': 'Estonia',
    'The Adults': 'New Zealand',
    'The Runaway Five': 'Canada',
    'u_mä': 'Spain',
    'Whiskerman': 'United States',
    '阿木': 'China',
    'A Cloud in Circle': 'Argentina',
    'Accordo dei contrari': 'Italy',
    'Aghast Manor': 'Norway',
    'Assorted Heap': 'Germany',
    'Earthrise': 'United States',
    'Elida Almeida': 'Cape Verde',
    'Elisabeth Ehrnrooth': 'Finland',
    'Essentials': 'United Kingdom',
    'Freedom Express': 'United States',
    'Gary Schocker': 'United States',
    'Group of 20': 'South Korea',
    'Headband': 'United States',
    'High Frequency': 'Italy',
    'Kappa': 'United States',
    'KillerBlood': 'Taiwan',
    'Klapto': 'Italy',
    'Moonoton': 'Russia',
    'Pink Milk': 'Sweden',
    'Sacrum': 'Poland',
    'Science Force': 'Italy',
    'The Day After': 'United States',
    'Zone Six': 'Germany',
    'ライフMIDI': 'United States',
    'Angel of Decay': 'United States',
    'BORO': 'Japan',
    'Black Temple': 'New Zealand',
    'Black Tooth': 'Turkey',
    'Bratex': 'Brazil',
    'Cassiopeia': 'Finland',
    'Creepmime': 'Netherlands',
    'Daco Junior': 'Finland',
    'Groovy Aardvark': 'Canada',
    'Johnoy Danao': 'Philippines',
    'Karel Goeyvaerts': 'Belgium',
    'Kayleigh Goldsworthy': 'United States',
    'Marvin Powell': 'United Kingdom',
    'Niño Zombi': 'Mexico',
    'The Get Go': 'United States',
    'Dad Thighs': 'Canada',
    '三浦理恵子': 'Japan',
    '門脇舞以': 'Japan',
    '齊豫': 'Taiwan',
    'Alana': 'United Kingdom',
    'Almost': 'Sweden',
    'Anna Prucnal': 'France',
    'Black Bottle Riot': 'Netherlands',
    'Blahalouisiana': 'Hungary',
    'Brett Kull': 'United States',
    'Brother Bones': 'United States',
    'Celestial Bums': 'Spain',
    'Creative Waste': 'Saudi Arabia',
    'DJ Smoke': 'France',
    'Des Demonas': 'United States',
    'Devour': 'United States',
    'Diabolus in Musica': 'France',
    'François Leleux': 'France',
    'Giulietta': 'Australia',
    'Goodbye Kumiko': 'United States',
    'In Your Face': 'United States',
    'Jim Gibson': 'United States',
    'Ky': 'United States',
    'Kytami': 'Canada',
    'Li Jianhong': 'China',
    'Look Back in Anger': 'United Kingdom',
    'Lucer': 'Denmark',
    'Mangled': 'United States',
    'NMR': 'Poland',
    'Nawlage': 'United States',
    '渡部龍': 'Japan',
    'Sofia Dragt': 'Netherlands',
    'The Topics': 'United States',
    'The Wipeouters': 'United States',
    'Weimar Gesang': 'Italy',
    'CHEN': 'South Korea',
    '1. Futurologischer Congress': 'Germany',
    'Ballerina Black': 'United States',
    'Brooklyn Dreams': 'United States',
    'Erin Ivey': 'United States',
    'Gert Steinbäcker': 'Austria',
    'heavytones': 'Germany',
    'Inch Chua': 'Singapore',
    'Jaguar Jaguar': 'Belgium',
    'Joey Kneiser': 'United States',
    'Jud Strunk': 'United States',
    'Laboratorija zvuka': 'Yugoslavia',
    'Los Chicros': 'France',
    'No Balls': 'Sweden',
    'Opened Paradise': 'Greece',
    'Paperhouse': 'Spain',
    'Ray Drummond': 'United States',
    'Red Cabin': 'United States',
    'Red Cardell': 'France',
    'Sailboats Are White': 'Canada',
    'Sauli Lehtonen': 'Finland',
    'Scott Kid': 'United States',
    'The Even Dozen Jug Band': 'United States',
    'The Gear': 'Australia',
    'The Star Department': 'Ireland',
    'Tonicha': 'Portugal',
    'Vlasta Popić': 'Croatia',
    'Rumba': 'Finland',
    'Angelika Köhlermann': 'Germany',
    'Ayla Shatz': 'Sweden',
    'Clashback': 'Estonia',
    'Fallen To': 'United Kingdom',
    'Irving Aaronson': 'United States',
    'Johnny London': 'United States',
    'Kenneth Fuchs': 'United States',
    'Lalalover': 'Belgium',
    'Mind Garage': 'United States',
    'MinstreliX': 'Japan',
    'Musta Kappeli': 'Finland',
    'Nems': 'United States',
    'Phosphorus': 'Canada',
    'Pretty Boy': 'United States',
    'Ronnie Liang': 'Philippines',
    'Strops': 'Latvia',
    'Tervahäät': 'Finland',
    'The Get': 'United Kingdom',
    'The Lee Thompson Ska Orchestra': 'United Kingdom',
    'The Orient Express': 'United States',
    'The Shallow Graves': 'Germany',
    'Yamataka Eye': 'Japan',
    "Aidan O'Rourke": 'United Kingdom',
    'Emperor Yes': 'United Kingdom',
    'Franck Vigroux': 'France',
    'Frank West': 'Germany',
    'Iva Lamkum': 'New Zealand',
    'Jacques Denjean': 'France',
    'Max Cavalera': 'Brazil',
    'Nathan Moore': 'United Kingdom',
    'Oiro': 'Germany',
    'Paul Peterson': 'United States',
    'Pijall': 'Finland',
    'Raycord': 'Canada',
    'Robert Klein': 'United States',
    'Spectateur': 'France',
    'Thomas Mann': 'Germany',
    '櫻井智': 'Japan',
    'Tre‐8': 'United States',
    'X Tracks': 'Italy',
    'Many Things': 'United Kingdom',
    '巫啟賢': 'Taiwan',
    '더 원': 'South Korea',
    'A Death for Every Sin': 'Canada',
    'Adalberto Álvarez': 'Cuba',
    'Arvi Lind': 'Finland',
    'MC B-Live': 'United Kingdom',
    'Corte dei miracoli': 'Italy',
    'DJ Black': 'Ghana',
    'Danish String Quartet': 'Denmark',
    'Emils': 'Germany',
    'Fire at Will': 'New Zealand',
    'Giao Linh': 'Vietnam',
    'Holiday Party': 'Australia',
    'Intense Hammer Rage': 'Australia',
    'Irek Dudek': 'Poland',
    'La Sra. Tomasa': 'Spain',
    'Leon Huff': 'United States',
    'MOON.74': 'Germany',
    'Mudweiser': 'France',
    'My Drug Hell': 'United Kingdom',
    'Niels Destadsbader': 'Belgium',
    'No Value': 'Japan',
    'Plastix': 'Austria',
    'Quincy Coleman': 'United States',
    'Rachael Price': 'United States',
    'Renato Figoli': 'Italy',
    'Riff Ruffin': 'United States',
    'Russ Abbot': 'United Kingdom',
    'Ryan Kisor': 'United States',
    'Star Academy 3': 'France',
    'The Lost': 'United States',
    'Urban Rejects': 'Germany',
    'Yo Camaleón': 'Mexico',
    '三月のパンタシア': 'Japan',
    'Amer Ammouri': 'Syria',
    'Antisilence': 'Turkey',
    'Bain Mattox': 'United States',
    'Banda de Pífanos de Caruaru': 'Brazil',
    "Brutus' Daughters": 'Spain',
    'Byrdie Green': 'United States',
    'Cupol': 'United Kingdom',
    'Della Bosiers': 'Belgium',
    'Loop Stepwalker': 'Spain',
    'Lucia Scansetti': 'Italy',
    'Mario Battaini': 'Italy',
    'Mirdza Zīvere': 'Latvia',
    'Miss Money': 'United States',
    'Moss Garten': 'Sweden',
    'Owl & the Pussycat': 'United States',
    'Qube': 'Poland',
    'Sexy Fi': 'Brazil',
    'Splattered': 'United States',
    'Virtraven Dream': 'Russia',
    'Yearbook Committee': 'United States',
    'Yonder Realm': 'United States',
    'Öris': 'Sweden',
    'Bass-X': 'United Kingdom',
    'Christian & die sauberen Jungs': 'Germany',
    'Eliza Hull': 'Australia',
    'Farolfi': 'Italy',
    'H.B. Barnum': 'United States',
    'Iqbal Bano': 'India',
    'James Armstrong': 'United States',
    'Karl Leister': 'Germany',
    'Kevin & Bean': 'United States',
    'LéOparleur': 'France',
    'Mattia Vlad Morleo': 'Italy',
    'Michel Cusson': 'Canada',
    'Proyecto Oniric': 'Spain',
    'Quadrivium': 'Norway',
    'Revolted Child': 'Russia',
    'Scare Dem Crew': 'Jamaica',
    'Shawn J Period': 'United States',
    'Slobobans Undergång': 'Sweden',
    'SONANCE': 'United Kingdom',
    'The Chakras': 'Ireland',
    'Valkyrend Varieté': 'Finland',
    'K-Swift': 'United States',
    'ÖfÖ Am': 'France',
    'ヴァルナ': 'Japan',
    '松永貴志': 'Japan',
    '黒色すみれ': 'Japan',
    'ABAKOS': 'Canada',
    'Andy J': 'Australia',
    'Antlered Man': 'United Kingdom',
    'Bella Vista': 'France',
    'Bukue One': 'United States',
    'Colja': 'Germany',
    'Corinna May': 'Germany',
    'Ella May Saison': 'Philippines',
    'Florent Vollant': 'Canada',
    'Gothic Girls': 'United Kingdom',
    'Harry Lubin': 'United States',
    'LADYBUG': 'Japan',
    'Ladybug': 'Taiwan',
    'Los Imposibles': 'Mexico',
    'MIC BANDITZ': 'Japan',
    'Michael Lucarelli': 'United States',
    'Minors': 'France',
    'Mixmaster Morris': 'United Kingdom',
    'MuseArtic': 'Netherlands',
    'Nono': 'France',
    'Orchestra del Teatro Comunale di Bologna': 'Italy',
    'Parker House and Theory': 'United States',
    'Stridsmenn': 'Norway',
    'Vijay Benedict': 'India',
    'Vishnudata': 'Finland',
    'Walter Scharf': 'United States',
    '好妹妹乐队': 'China',
    '木野寧': 'Japan',
    '패닉': 'South Korea',
    '5R6': 'Ukraine',
    'Anatomy of Habit': 'United States',
    'Axehandle': 'United States',
    'Colin Macleod': 'United Kingdom',
    'Dub Orchestra': 'France',
    'Egyptian Project': 'France',
    'Francesco Nuti': 'Italy',
    'Free Deejays': 'Romania',
    'Hempress Sativa': 'Jamaica',
    'Katzen Kapell': 'Sweden',
    'Kulkija': 'Finland',
    'Omophagia': 'Switzerland',
    'Paul Sabu': 'United States',
    'Perfect Chaos': 'Finland',
    'Robert Shaw Festival Singers': 'United States',
     'Carpathia': 'Slovakia',
    'Cartographs': 'Denmark',
    'Conscientia Peccati': 'Germany',
    'Dan Sullivan’s Shamrock Band': 'United States',
    'Despe e Siga': 'Portugal',
    'Dios/シグナルP': 'Japan',
    'District 7': 'Canada',
    'Erdve': 'Lithuania',
    'GRRRL PRTY': 'United States',
    'Janie Jones': 'United Kingdom',
    'Jon Nørgaard': 'Denmark',
    'Juggling Jugulars': 'Finland',
    'KNOCK OUT MONKEY': 'Japan',
    'Kaarle Viikate': 'Finland',
    'Karl-Birger Blomdahl': 'Sweden',
    'Mary Halvorson Octet': 'United States',
    'Micke from Sweden': 'Sweden',
    'Mr.K': 'United States',
    'Natisú': 'Chile',
    'New Grenada': 'United States',
    'O.O.O.': 'United Kingdom',
    'Grégory Darsa': 'France',
    'Raging Moses': 'United States',
    'Spacegoat': 'Mexico',
    'The Lackloves': 'United States',
    'Toby Gale': 'United Kingdom',
    'United Fruit': 'United Kingdom',
    'Yeyo': 'Spain',
    'Zulma Yugar': 'Bolivia',
    'Aystar': 'United Kingdom',
    'Bayside Kings': 'Brazil',
    'Black Moon Circle': 'Norway',
    'Curly Curve': 'Germany',
    'Fill': 'Russia',
    'Gjermund Larsen': 'Norway',
    'Gladenfold': 'Finland',
    'Harmony Woods': 'United States',
    'Jake&Papa': 'United States',
    'Kamara': 'Finland',
    'Let Me Dream': 'Finland',
    'Lifeforce': 'United Kingdom',
    'Martina Schwarzmann': 'Germany',
    'Michael James Scott': 'United States',
    'Richard Poon': 'Philippines',
    'Seelenheil': 'Russia',
    'Silver Cat': 'Jamaica',
    'Smoke Like a Fish': 'United Kingdom',
    'Sundry': 'Estonia',
    'The Amorettes': 'United Kingdom',
    'The Atmospheres': 'United States',
    'The Inflatable Sideshow': 'United Kingdom',
    'Ulrike Haage': 'Germany',
    'Yeskim': 'Netherlands',
    '土屋憲一': 'Japan',
    'Alexandre Dossin': 'Brazil',
    'Armands': 'Latvia',
    'Asprilio Pacelli': 'Italy',
    'Brian Evans': 'Australia',
    'Cadalack Ron': 'United States',
    'Cadence Spalding': 'United States',
    'Carl Heinrich Graun': 'Germany',
    'Erfolg': 'Germany',
    'Essra Mohawk': 'United States',
    'Gerardo Enciso': 'Mexico',
    'Giacomo Aragall': 'Spain',
    'H-Block 101': 'Australia',
    'Harker': 'United Kingdom',
    'High Hill': 'Brazil',
    'I Spit Ashes': 'Germany',
    'Killer Aspect': 'Finland',
    'Mike Mills': 'United States',
    'Moka DJ': 'Italy',
    'Mover': 'United States',
    'MOÑIGO': 'Spain',
    'Ngobo Ngobo': 'Germany',
    'Rube Bloom': 'United States',
    'Wolf Ram Heart': 'United States',
    'Starman Jr.': 'United States',
    '堀江淳': 'Japan',
    '金田朋子': 'Japan',
    'Al Scorch': 'United States',
    'Bitterness': 'Italy',
    'Black Channels': 'United Kingdom',
    'Cóndor Jet': 'Chile',
    'DML': 'Germany',
    'Hayward Williams': 'United States',
    'Hornpipe2': 'United States',
    'James Adams': 'United Kingdom',
    'Kelroy': 'United States',
    'Lew Tabackin': 'United States',
    'Lukas Ligeti': 'Austria',
    'Manic Sheep': 'Taiwan',
    'Mr Morse': 'Ukraine',
    'Park Avenue Playground': 'United States',
    'Picard Brothers': 'France',
    'Sam Woolf': 'United States',
    'Spectaculatius': 'Germany',
    'The Barmitzvah Brothers': 'Canada',
    'The Burning Souls': 'Jamaica',
    'Trama': 'Italy',
    'Waldjinah': 'Indonesia',
    'We Will Fly': 'Germany',
    '中山千夏': 'Japan',
    '前野健太': 'Japan',
    '徐誉滕': 'China',
    '進行方向別通行区分': 'Japan',
    'Ahimsa': 'Poland',
    'Bitori': 'Cape Verde',
    'Barrence Whitfield': 'United States',
    'Bret Easton Ellis': 'United States',
    'C.O.M.A.': 'Germany',
    'Cavus': 'Finland',
    'Chris Cauley': 'United States',
    'Dirty K': 'United Kingdom',
    'Ecliptica': 'Austria',
    'Hans Werner Olm': 'Germany',
    'Ian Snyder': 'United States',
    'Ivy Green': 'Netherlands',
    'Jakk Frost': 'United States',
    'Jimmy Carl Black': 'United States',
    'Jouis': 'United Kingdom',
    'Kaija Kärkinen & Ile Kallio': 'Finland',
    'Ladies W.C.': 'Venezuela',
    'Les Djinns': 'Algeria',
    'Mathias Kom': 'Canada',
    'May Day': 'Italy',
    'Mikołaj Bugajak': 'Poland',
    'Noé Willer': 'France',
    'Ondřej Havelka a jeho Melody Makers': 'Czech Republic',
    'Pascal Mollin': 'Germany',
    'Pierre Michelot': 'France',
    'Roel Salemink': 'Netherlands',
    'Stuart McLean': 'Canada',
    'Tetraktys': 'France',
    'The Crocodiles': 'New Zealand',
    'The Gosdin Brothers': 'United States',
    'Tommie': 'Netherlands',
    'West Coast All Stars': 'United States',
    'Baby Chaos': 'United Kingdom',
    'Battered': 'Norway',
    'Blitz//Berlin': 'Canada',
    'Carlos Gomes': 'Portugal',
    'David Nall': 'United States',
    'Dischord': 'United Kingdom',
    'Dorincourt': 'Germany',
    'Guy Blakeslee': 'United States',
    'Hesian': 'Spain',
    'Jim Suhler & Monkey Beat': 'United States',
    'José Capmany': 'Costa Rica',
    'K-MASERA': 'Japan',
    'Life... But How to Live It?': 'Norway',
    'Lisa Børud': 'Norway',
    'Lithe': 'Australia',
    'Loosely Tight': 'United States',
    'Maggie Estep': 'United States',
    'Magnificent Muttley': 'Poland',
    'Monstrare': 'United States',
    'Ninnuam': 'Sweden',
    'Nona Gaye': 'United States',
    'Orquesta Gitano': 'United States',
    'Phillip Frazer': 'Jamaica',
    'Rocky Gresset': 'France',
    'Ruy Maurity': 'Brazil',
    'Salomon': 'Finland',
    'September Leaves': 'Germany',
    'Sheila Mello': 'Brazil',
    'Stephanie de Sykes': 'United Kingdom',
    'The Shadow Order': 'Greece',
    'Tight': 'United States',
    'Valor': 'Greece',
    'Yves Paquet': 'Belgium',
    'Đức Tuấn': 'Vietnam',
    'Andrzej Ozga': 'Poland',
    'Badbug': 'Switzerland',
    'Christian Epidemic': 'Hungary',
    'Deus Meus': 'Poland',
    'Doc Ish': 'United States',
    'Edward Zwick': 'United States',
    'Euson': 'Netherlands',
    'Excizen': 'Serbia',
    'Exit the King': 'United States',
    'Fred Gerlach': 'United States',
    'Gardland': 'United States',
    'Harlow': 'Canada',
    'Hattrick': 'Czech Republic',
    'Jérémie Rhorer': 'France',
    'Karel Velebny': 'Czech Republic',
    'Luckless': 'New Zealand',
    'MashmyAs$': 'Brazil',
    'Nick Harris': 'United Kingdom',
    'Sara Lowes': 'United Kingdom',
    'The Brotherhood of Lizards': 'United Kingdom',
    'The Lost & Found': 'United States',
    'Vital Farias': 'Brazil',
    'BellaMaine': 'United States',
    'Bening': 'Indonesia',
    'Bread Pilot': 'United States',
    'Carnival of Dreams': 'Germany',
    'Champian Fulton': 'United States',
    'control.org': 'United States',
    'EurythmY': 'United Kingdom',
    'Gangrena': 'Mexico',
    'Heather Victoria': 'United States',
    'The Jazz Passengers': 'United States',
    'Not Real Presence': 'Spain',
    'Obsil': 'Italy',
    'Onward, Soldiers': 'United States',
    'Orkun Tüzel': 'Turkey',
    'Robert Lopez': 'United States',
    'Spiralmouth': 'United States',
    'Spritney Bears': 'Norway',
    'Teenage Rehab': 'United States',
    'The Bayonets': 'Serbia',
    'The Shipyard': 'Poland',
    'Trzy Majtki': 'Poland',
    'Молотов Коктейль': 'Russia',
    'Black Tie Revue': 'United States',
    'Blood Island Raiders': 'United Kingdom',
    'Bläck Rokit': 'Estonia',
    'Carlotta': 'Italy',
    'Carol Grimes': 'United Kingdom',
    'David Lewiston': 'United Kingdom',
    'Dick Cavett': 'United States',
    'Flirt': 'Slovenia',
    'Freedumb': 'Norway',
    'Kinzy': 'United Kingdom',
    'La Perla de Cádiz': 'Spain',
    'Manu Militari': 'Canada',
    'Maria Stenz': 'Denmark',
    'Marmalade butcher': 'Japan',
    'Me for Rent': 'Italy',
    'Mike D': 'United States',
    'Milkywhale': 'Iceland',
    'MonkeyJunk': 'Canada',
    'Monsieur Jeffrey Evans': 'United States',
    'Moonkyte': 'United Kingdom',
    'No Tide': 'United States',
    'Noxa': 'Indonesia',
    'Oto Hiax': 'United Kingdom',
    'Pip Proud': 'Australia',
    'Regulator Watts': 'United States',
    'Rydell': 'Canada',
    'Wayne G': 'United Kingdom',
    '本木咲黒': 'Japan',
    '櫻川めぐ': 'Japan',
    'ABISHA': 'United Kingdom',
    'Alvaro Amici': 'Italy',
    'Anneli Sari': 'Finland',
    'Atolah': 'Australia',
    'Barrelhouse': 'Netherlands',
    'Billy Jonas': 'United States',
    'Charge Group': 'Australia',
    'Cyril Watters': 'United Kingdom',
    'Giorgio Consolini': 'Italy',
    'Haters': 'Australia',
    'Jimi Constantine': 'Finland',
    'Mark Abis': 'United Kingdom',
    'Michiel van Erp': 'Netherlands',
    'Михаил Михайлович Ипполитов‐Иванов': 'Russia',
    'Mofagang': 'Germany',
    'Owen Ovadoz': 'South Korea',
    'Pinwheel': 'United States',
    'Ritual Mess': 'United States',
    'Salem Mass': 'United States',
    'Smoking Spore': 'United States',
    'Social Junk': 'United States',
    'Steve Howe’s Remedy': 'United Kingdom',
    'Tesox': 'Germany',
    'The Grace Thrillers': 'Jamaica',
    'Bhonus': 'Sweden',
    'Brett James': 'United States',
    'Chaplain': 'France',
    'Charlotte Carpenter': 'United Kingdom',
    'Clay Hips': 'Germany',
    'Daniel Roeth': 'Russia',
    'Dirty Blues Band': 'United States',
    'Homemade': 'Italy',
    'Jamie Hartman': 'United Kingdom',
    'Just Mike': 'Germany',
    'Kink Ador': 'United States',
    'Lancaster': 'Spain',
    'Larry Dale': 'United States',
    'Loud Lary Ajust': 'Canada',
    'Makesome Breaksome': 'United Kingdom',
    'Martha Veléz': 'United States',
    'MayMay': 'United States',
    'Mike Leander': 'United Kingdom',
    'Nicos Gun': 'United States',
    'Neoton Familia': 'Hungary',
    'Nocturnal Fear': 'United States',
    'Nojda': 'Russia',
    'Nucksal': 'South Korea',
    'Oh! Dee': 'Russia',
    'OncetheSun': 'United States',
    'PERESTROÏKA': 'Japan',
    'Philip Lasser': 'United States',
    'Rachel Lloyd': 'United Kingdom',
    'Richard Rossbach': 'Germany',
    'Roland Schwarz': 'Austria',
    'Saxon Lee & the Shadows International': 'Nigeria',
    '낯선': 'South Korea',
    'Alyssa Milano': 'United States',
    'Bill Doss': 'United States',
    'Brett Newski': 'United States',
    'Cara Hammond': 'United Kingdom',
    'Eulorhythmics': 'United States',
    'Fantine': 'Australia',
    'Gustavo Galindo': 'Mexico',
    'Harm/Shelter': 'Germany',
    '佐藤ひろのすけ': 'Japan',
    'Karina Gauvin': 'Canada',
    'Kim McAuliffe': 'United Kingdom',
    'Krokofant': 'Norway',
    'Malladi Brothers': 'India',
    'Masqualero': 'Norway',
    'Missing Links': 'France',
    'Moonflower': 'Netherlands',
    'Petros Klampanis': 'Greece',
    'Pitch Twit': 'United Kingdom',
    'Random Mullet': 'Finland',
    'Rings of Rhea': 'Ukraine',
    'Siti Badriah': 'Indonesia',
    'Sugus': 'Spain',
    'Trizna': 'Russia',
    'Tyler Dickerson': 'United States',
    'Weeping Silence': 'Malta',
    'Сергей Старостин': 'Russia',
    'ザ・ワイルド・ワンズ': 'Japan',
    '奥村初音': 'Japan',
    '揺らぎ': 'Japan',
    '森昌子': 'Japan',
    'Amor & Die Kids': 'East Germany',
    'Angelo Francesco Lavagnino': 'Italy',
    'Ash of Ashes': 'Germany',
    "B'eirth": 'United States',
    'Beelzefuzz': 'United States',
    'Beluga': 'United Kingdom',
    'Blue Smitty': 'United States',
    'Breezer': 'Cyprus',
    'Bérangère Palix': 'France',
    'Culper Ring': 'United States',
    'Drained Scorn': 'Argentina',
    'Eero Koivistoinen Music Society': 'Finland',
    'Foot Patrol': 'United States',
    'Gargantua': 'Poland',
    'Glamour': 'Spain',
    'Koyaanisqatsi': 'Spain',
    'Musical Blades': 'United States',
    'Starchitect': 'Ukraine',
    'Stickman': 'United States',
    'Tempestuous Fall': 'Australia',
    'The Ebb and Flow': 'United States',
    'Tim Russ': 'United States',
    'Toni Leys': 'Argentina',
    'Triskell': 'France',
    'Trịnh Công Sơn': 'Vietnam',
    'Turpentine Brothers': 'United States',
    'Wylhelm': 'United Kingdom',
    'Adot Upt': 'United States',
    'Alice Spacedoll': 'Australia',
    'Arkon': 'Australia',
    'Austin Collins': 'United States',
    'Christopher Willis': 'United States',
    'Dieter Ilg': 'Germany',
    'Disjecta Membra': 'New Zealand',
    'Fallible': 'United States',
    'Fetchin Bones': 'United States',
    'Fricción': 'Argentina',
    'Govannen': 'United Kingdom',
    'Greenwood Sharps': 'United Kingdom',
    'Incapacity': 'Sweden',
    'Jay Wiggins': 'United States',
    'Kay Thompson': 'United States',
    'Kenny Roberts': 'United States',
    'Kingfisha': 'Australia',
    'LOCAL CONNECT': 'Japan',
    'Le 6-9': 'France',
    'Leo Laker': 'Finland',
    'María Cristina Kiehr': 'Argentina',
    'Ramona Gonzalez': 'United States',
    'Richard Coleman': 'Argentina',
    'SUGIZO & THE SPANK YOUR JUICE': 'Japan',
    'sumiisan': 'Japan',
    'Sylvi Foster': 'Italy',
    'Symbolyc One': 'United States',
    'Tengwar': 'Argentina',
    'The Hot Rod Gang': 'Germany',
    'Thom Green': 'United States',
    'Tribe of Gypsies': 'United States',
    "Uncreation's Dawn": 'Finland',
    'Vincent Baguian': 'France',
    'Ward Churchill': 'United States',
    '7 Walkers': 'United States',
    'Astoveboat': 'United States',
    'Astræa': 'United Kingdom',
    'Clive Wright': 'United States',
    'Common Loon': 'United States',
    'Construction': 'Netherlands',
    'Dave Hunt': 'United States',
    'Deep South': 'Bolivia',
    'Dekoder': 'Canada',
    'Escuchando Elefantes': 'Spain',
    'Guille El Invencible': 'Spain',
    'Hermanos Guarennes': 'Chile',
    'Joe Thompson': 'United States',
    'John Lee': 'China',
    'Kasia i Wojtek': 'Poland',
    'Kid Theodore': 'United States',
    'Kohti Tuhoa': 'Finland',
    'Mike Miller': 'Germany',
    'muddasheep': 'Austria',
    'Neil Campbell': 'United Kingdom',
    'Noizekid': 'Mexico',
    'PIM': 'Finland',
    'Pim': 'Belgium',
    'Seamus': 'Finland',
    'Sötlimpa': 'Sweden',
    'The Artisans': 'United Kingdom',
    'The Steinbecks': 'Australia',
    'Choir of York Minster': 'United Kingdom',
    'Szopeen': 'Poland',
    'Adam Selzer': 'United States',
    'Boxia': 'United Kingdom',
    'Don Taylor': 'United States',
    'Goldman': 'United Kingdom',
    'Graveyard Shift': 'United States',
    'Hans-Christoph Becker-Foss': 'Germany',
    'Jan Gustafsson': 'Sweden',
    'KAO': 'Japan',
    'Kao': 'Germany',
    'Keep Razors Sharp': 'Portugal',
    'Kreativ in den Boden': 'Italy',
    'La Caja Negra': 'Spain',
    'Richard Jon Smith': 'South Africa',
    'Shoo': 'South Korea',
    'Somedaydream': 'Philippines',
    'The Axel Boys Quartet': 'Denmark',
    'The Creetins': 'Germany',
    'Ulla Norden': 'Germany',
    'dreDDup': 'Serbia',
    '・・・・・・・・・': 'Japan',
    '何勇': 'China',
    'Acre Yawn': 'United States',
    'Andy Forray': 'United Kingdom',
    'BNLX': 'United States',
    'Bent Sørensen': 'Denmark',
    'Boy + Kite': 'United States',
    'Cartilage': 'United Kingdom',
    'Drunken Dolly': 'Netherlands',
    'Herbst': 'Germany',
    'Hooray for Humans': 'Ireland',
    'J.J. Jones': 'United States',
    'Jamie Meyer': 'Sweden',
    'Justin(e)': 'France',
    'Kardemimmit': 'Finland',
    'Lumikide': 'Norway',
    'Mortuus Infradaemoni': 'Germany',
    'Negligence': 'Slovenia',
    'Peter Laughner': 'United States',
    'Post Human Era': 'United States',
    'Price of Blood': 'Canada',
    'René la Taupe': 'France',
    'Rowan': 'United States',
    'Screen Prints': 'United Kingdom',
    'Selen Gülün': 'Turkey',
    'Smaller': 'United Kingdom',
    'Subfiltronik': 'United Kingdom',
    'Sôra': 'France',
    'Vardan': 'Italy',
    'Γιάννης Κότσιρας': 'Greece',
    'Страмослябы': 'Russia',
    'ばんばひろふみ': 'Japan',
    'ジャッキー吉川とブルー・コメッツ': 'Japan',
    'Albert Linder': 'Denmark',
    'Beer Goggles': 'Australia',
    'Complicated': 'Israel',
    'Cracked Actor': 'United States',
    'Dut': 'Spain',
    'Elisa Gabbai': 'Israel',
    'Eric Watson': 'United States',
    'Fatal Charm': 'United Kingdom',
    'Giant Crab': 'United States',
    'High Five Quintet': 'Italy',
    'Janusz Popławski': 'Poland',
    'Kiggen': 'South Korea',
    'Liquid Crystal': 'Russia',
    'Megaslaughter': 'Sweden',
    'Nora Norman': 'Spain',
    'Nuevenoventaicinco': 'Spain',
    'Parliament-Funkadelic': 'United States',
    'Planet Gong': 'Netherlands',
    'RedHook': 'Australia',
    'Rêverie': 'Italy',
    'SHALT': 'Switzerland',
    'Simon Stålenhag': 'Sweden',
    'Tarantulaz': 'United Kingdom',
    'The Crescents': 'United States',
    'The Unfolding': 'United States',
    'Ale Aguirre': 'Mexico',
    'The Alienator': 'Netherlands',
    'Axonic': 'Germany',
    'Bernard Xolotl': 'France',
    'Buon vecchio Charlie': 'Italy',
    'Cama de Gato': 'Brazil',
    'Don Esteban': 'Germany',
    'Electric Red': 'United Kingdom',
    'God Is LSD': 'Germany',
    'Haüer': 'Ireland',
    'Jim Pepper': 'United States',
    'John Andrews Tartaglia': 'United States',
    'John Proulx': 'United States',
    'Kastrierte Philosophen': 'Germany',
    'Lollievox': 'United States',
    'Luke Jackson': 'United Kingdom',
    'Marchello': 'United States',
    'Mayonesa': 'Uruguay',
    'Mekanik Disorder': 'Spain',
    'My Early Mustang': 'Germany',
    'Oddities': 'Canada',
    'Peter Cusack': 'United Kingdom',
    'Plan 4': 'Argentina',
    'Seán Ryan': 'Ireland',
    'Sleeptalker': 'United States',
    'The Primevals': 'United Kingdom',
    'The Vittupäät': 'Finland',
    'Tipe Johnson': 'Finland',
    'Tredje Mannen': 'Sweden',
    'Valezka': 'Germany',
    '五島良子': 'Japan',
    '水中、それは苦しい': 'Japan',
    'A Dark Orbit': 'United States',
    "Annie's Black": 'Japan',
    'Arnaldo Cohen': 'Brazil',
    'Bambole di pezza': 'Italy',
    'Barbara Krafftówna': 'Poland',
    'Brigitte Boisjoli': 'Canada',
    'CAPTAIN HEDGE HOG': 'Japan',
    'Chiefs of Relief': 'United Kingdom',
    'Claire Michelle': 'United States',
    'Cæsar': 'Denmark',
    'David Chappell': 'United Kingdom',
    'Encounter': 'Estonia',
    'Hege Rimestad': 'Norway',
    'Infinitum Obscure': 'Mexico',
    'Kevin Puts': 'United States',
    'Little Gold': 'United States',
    'Masanori Yasuda': 'Japan',
    'Paul Droid': 'Spain',
    'Stephen Hill': 'United States',
    'Strawberry Path': 'Japan',
    'Ståålfågel': 'Sweden',
    'Takeshi Muto': 'United States',
    'The Asha Experiment': 'United States',
    'The Chosen': 'United States',
    'Whorl': 'United States',
    'Zsédenyi Adrienn': 'Hungary',
    'Orbit Over Luna': 'Canada',
    'Нечто': 'Russia',
    '水蓮寺ルカ': 'Japan',
    '關智斌': 'China',
    'Big Hollis': 'United States',
    'BlöödHag': 'United States',
    'Brian Matthew': 'United Kingdom',
    'Carrie Mac': 'United Kingdom',
    'Charlie Pickett': 'United States',
    'Clown Alley': 'United States',
    'Jai McDowall': 'United Kingdom',
    'Jetsex': 'France',
    'Kitty & the K': 'Sweden',
    'Linda de Suza': 'Portugal',
    'Maria False': 'France',
    'Marie Carmen': 'Canada',
    'Orkus': 'Germany',
    'Parasol Caravan': 'Austria',
    'René Amesz': 'Netherlands',
    'Sacred Denial': 'United States',
    'Simone Angel': 'Netherlands',
    'Sonya Isaacs': 'United States',
    'T.C.': 'United States',
    'The Blackberries': 'Germany',
    'The York Brothers': 'United States',
    'Auntie Christ': 'United States',
    'Banda do casaco': 'Portugal',
    'DJ Grazzhoppa': 'Belgium',
    'Double Pleasure': 'Belgium',
    'Hal Harris': 'United States',
    'Houston Wells & The Marksmen': 'United Kingdom',
    'Hypnotic Hysteria': 'Italy',
    'Imascore': 'Germany',
    'Jacek Kochan': 'Poland',
    'Johnny Whitney': 'United States',
    'Kingdom Crumbs': 'United States',
    'L.A.M.F.': 'Finland',
    'Moonfog': 'Slovakia',
    'NeiRula': 'Ukraine',
    'Pepe Lota': 'Chile',
    'Queens of Noize': 'United Kingdom',
    'Samson Jones': 'Germany',
    'Sector 516': 'Russia',
    'Steve Peters': 'United States',
    'Suat Sayın': 'Turkey',
    'Sun K': 'Canada',
    'The Beakers': 'United States',
    'Thomas Hardy': 'United Kingdom',
    'Ада Якушева': 'Russia',
    'Нокаут': 'Russia',
    '신용재': 'South Korea',
    'A Handful of Dust': 'New Zealand',
    'APA': 'Finland',
    'Ann Magnuson': 'United States',
    'Balgeroth': 'Germany',
    'Christian Fitness': 'United Kingdom',
    'Corrosive Carcass': 'Sweden',
    'Divorcee': 'United States',
    'Edith Wilson': 'United States',
    'Filipe Pinto': 'Portugal',
    'Fireballet': 'United States',
    'Folk Family Revival': 'United States',
    'Galus': 'Poland',
    'Gypsy Rose': 'Canada',
    'Intermezzo': 'Sweden',
    'Karl Berger': 'Germany',
    'Lamentations of the Ashen': 'United States',
    'Marjorie Biondo': 'Italy',
    'Natalie Stovall and The Drive': 'United States',
    'Quire of Voyces': 'United States',
    'Red Sun Revival': 'United Kingdom',
    'Sacral Rage': 'Greece',
    'Schattenvald': 'Germany',
    'Select Project': 'Russia',
    'Sentidos Apuestos': 'Mexico',
    'Stephanie McCallum': 'Australia',
    'The Assembled Multitude': 'United States',
    'Torturer': 'Chile',
    'Urban Dogs': 'United Kingdom',
    'Will Brandes': 'Germany',
    'Ghost Estates': 'Ireland',
    'NNY': 'Portugal',
    '이병우': 'South Korea',
    'Ashmont Hill': 'United States',
    'Alex Barnett': 'United States',
    'Coope Boyes & Simpson': 'United Kingdom',
    'D.C. Lewis': 'Netherlands',
    'Da Circle': 'United States',
    'Dave Graney': 'Australia',
    'Diabolo': 'France',
    'Ende': 'France',
    'Eptos Uno': 'Mexico',
    'Eric Kloss': 'United States',
    'Fernando Varela': 'United States',
    'Ghalia Benali': 'Belgium',
    'Jon Appleton': 'United States',
    'Julie B. Bonnie': 'France',
    'King Lizard': 'United Kingdom',
    'Lazy Lizzard Gang': 'Germany',
    'Les Jaguars': 'Canada',
    'Melted Space': 'France',
    "Pedro's Heavy Gentlemen": 'Finland',
    'Rigoletto': 'Germany',
    'Roberto Cantoral': 'Mexico',
    'Roman Bosski & Piero': 'Poland',
    'The Good Girls': 'United States',
    'The New London Orchestra': 'United Kingdom',
    'Toe Fat': 'United Kingdom',
    '村上信五': 'Japan',
    '芳野藤丸': 'Japan',
    '이달의 소녀 1/3': 'South Korea',
    'Anapilis': 'Lithuania',
    'Annalisa Tornfelt': 'United States',
    'Awlnight': 'Belarus',
    'Carpathian Full Moon': 'Norway',
    'Chuzpe': 'Austria',
    'D_2': 'Bulgaria',
    'Gore Gore Gays': 'Spain',
    'Heather Williams': 'United States',
    'Hugh Blumenfeld': 'United States',
    'Infected Flesh': 'Spain',
    'Jean-Michel Aweh': 'Germany',
    'John Basile': 'United States',
    'KVKA': 'New Zealand',
    '宮内庁楽部': 'Japan',
    'Melomani': 'Poland',
    'Mondvolland': 'Netherlands',
    'Neutral Lies': 'France',
    'Paulo': 'Spain',
    'Pickers': 'Germany',
    'RAY-GUNS': 'Japan',
    'Seawolves': 'Switzerland',
    'Sex Hands': 'United Kingdom',
    'Shoshana Michel': 'United States',
    'The Brainkiller': 'Spain',
    'Woody & Paul': 'Netherlands',
    'Yeah Jazz': 'United Kingdom',
    'Arbete & fritid': 'Sweden',
    'Bobby Chiz': 'United States',
    'Burning Caravan': 'Colombia',
    'Cindy Daniel': 'Canada',
    'Don Diego': 'Sweden',
    'Euforia': 'Estonia',
    'Hugo Race + True Spirit': 'Australia',
    'Johan Kvandal': 'Norway',
    'Little Mike & The Tornadoes': 'United States',
    'Louise Rademakers': 'Netherlands',
    'Nichts gelernt': 'Germany',
    'Nicolas Falcon': 'Italy',
    'Nollores': 'United Kingdom',
    'Ρένα Κυριακού': 'Greece',
    'Smooth Ace': 'Japan',
    'Steve Weisberg': 'United States',
    'Sugluk': 'Canada',
    'The Cretins': 'New Zealand',
    'The Dantes': 'United States',
    'Larbanois & Carrero': 'Uruguay',
    '四条貴音': 'Japan',
    '紅い流星': 'Japan',
    'Audioroom': 'France',
    'Blackness': 'Indonesia',
    'Cheryl Gunn': 'United States',
    'Chilled Monkey Brains': 'United States',
    'Cyklon B': 'Sweden',
    'Die kleine Tierschau': 'Germany',
    'Mr. Burns': 'United Kingdom',
    'Oxy': 'Brazil',
    'Panda Valium': 'France',
    'Rosa Lee Hill': 'United States',
    'Schola Cantorum Basiliensis': 'Switzerland',
    'Soul Supreme': 'Sweden',
    'Sour Grapes': 'United Kingdom',
    'Terry MacAlmon': 'United States',
    'The Stop the Violence Movement': 'United States',
    'The Wolves of Avalon': 'United Kingdom',
    'Total Shutdown': 'United States',
    'Тина Кузнецова': 'Russia',
    'Aminata Savadogo': 'Latvia',
    'Austin Cunningham': 'United States',
    'Clotted Symmetric Sexual Organ': 'Japan',
    'Daniel Gildenlöw': 'Sweden',
    'Doctor Clayton': 'United States',
    'Evan LE NY': 'France',
    'FLR': 'Japan',
    'Glyndebourne Chorus': 'United Kingdom',
    'Il Vaselino': 'Finland',
    'John Jacob Magistery': 'Canada',
    'Joseíto Mateo': 'Dominican Republic',
    'KAmiYU': 'Japan',
    'Markandeya dasa': 'Germany',
    'Myalansky': 'United States',
    'Mylon LeFevre': 'United States',
    'Notions': 'Germany',
    'P.J. Pacifico': 'United States',
    'Pandas & People': 'United Kingdom',
    'Sea of Trees': 'Netherlands',
    'The Embraced': 'Norway',
    '3 Balls of Fire': 'United States',
    'A.A.Williams': 'United Kingdom',
    'Antoine Beuger': 'Netherlands',
    'Athome Project': 'Norway',
    'Bishop G': 'United States',
    'Bloody Sign': 'France',
    'Benjamin Ball': 'South Africa',
    'Blood & Roses': 'United Kingdom',
    'Brick Top Blaggers': 'United States',
    'Chris Leslie': 'United Kingdom',
    'Desorden': 'Spain',
    'Dominique Vellard': 'France',
    'Electrozombies': 'Chile',
    'Elements of Need': 'United States',
    'Employer, Employee': 'United States',
    'Evaluna Montaner': 'Venezuela',
    'Frances White': 'United States',
    'Ginette Garcin': 'France',
    'Grind': 'Denmark',
    'House of LaDosha': 'United States',
    'Jorge Luis Borges': 'Argentina',
    'Symbiz Sound': 'Germany',
    'Snoretex': 'United Kingdom',
    'Soulbrotha': 'Germany',
    'Tango Siempre': 'United Kingdom',
    'Tommy Jarrell': 'United States',
    'Unsacred Hearts': 'United States',
    'Violet Bones': 'United Kingdom',
    'A12': 'Belgium',
    'Agarrate Catalina': 'Uruguay',
    'Alan Feinberg': 'United States',
    'Angel 1': 'United States',
    'Bella Donna': 'Germany',
    "Creation's End": 'United States',
    'Dan Stuart': 'United States',
    'Danso': 'United Kingdom',
    'Fresh Life Worship': 'United States',
    'Gardening by Moonlight': 'United Kingdom',
    'Ghost Thrower': 'United States',
    'Gianni Bini': 'Italy',
    'Johann Wilhelm Hertel': 'Germany',
    'Mal Etre': 'Switzerland',
    'Moe Koffman': 'Canada',
    'Port of Harlem Jazzmen': 'United States',
    'Ricardo Garduno': 'Mexico',
    'Semmangudi Srinivasa Iyer': 'India',
    'Shannon McArdle': 'United States',
    'Swans of Avon': 'Germany',
    'The Bad Rackets': 'United States',
    'The Dog and Everything': 'United States',
    'Tinkerbells Fairydust': 'United Kingdom',
    "Tyran' Pace": 'Germany',
    'U-Tek': 'Germany',
    'Wonder Boyz': 'South Korea',
    'Или': 'Russia',
    'みーちゃん': 'Japan',
    '久宝留理子': 'Japan',
    '니콜': 'South Korea',
    'Aby': 'India',
    'Alex Santer': 'Greece',
    'Amos Garrett': 'Canada',
    'Benjamin Paulin': 'France',
    'Cinemuerte': 'Portugal',
    'Guitar Crusher': 'United States',
    'I Promised Once': 'Japan',
    'Johnny Bravo': 'Slovenia',
    'L’Assemblée': 'Canada',
    'Lasse K': 'Finland',
    'María Grever': 'Mexico',
    'Matteo Scumaci': 'United Kingdom',
    'Michael Prime': 'United Kingdom',
    'River Styx': 'United Kingdom',
    'Rumatera': 'Italy',
    'Salzburger Kammerorchester': 'Austria',
    'Steve Wood': 'United States',
    'Sunstream': 'Estonia',
    'Taipuva Luotisuora': 'Finland',
    '東祥高': 'Japan',
    'Zig Ziglar': 'United States',
    'kls.': 'Finland',
    'Лето': 'Belarus',
    'Ad Vielle Que Pourra': 'Canada',
    'Aguynguerran': 'Belgium',
    'Al Urban': 'United States',
    'Bow Low': 'France',
    'Dark Furs': 'United States',
    'Emir Kusturica': 'Serbia',
    'Hugin Munin': 'Brazil',
    'Just Banco': 'United Kingdom',
    'Knivderby': 'Sweden',
    'MOONOVERSUN': 'United Kingdom',
    'Markus Perttula': 'Finland',
    'Momotaro': 'United Kingdom',
    'National Dust': 'United States',
    'Ramy Essam': 'Egypt',
    'Reserve': 'United Kingdom',
    'Rob Rio': 'United States',
    'Szécsi Pál': 'Hungary',
    'The Brickbats': 'United States',
    'The Jellybricks': 'United States',
    'The Jordans': 'Brazil',
    'The Thunderbeats': 'Russia',
    'Twisted Perspective': 'India',
    'שלומי שבת': 'Israel',
    '近藤晃央': 'Japan',
    '9West': 'Greece',
    'Anti Establishment': 'United Kingdom',
    'Antti Sarpila': 'Finland',
    'Beeres': 'Poland',
    'Carlos Salzedo': 'France',
    'Cirwo': 'Japan',
    'Duina del Mar': 'Colombia',
    'Ebo Taylor & The Pelicans': 'Ghana',
    'Evan Peters': 'United States',
    'Freestone': 'United States',
    'Hell:on': 'Ukraine',
    'Hugh Gunnell': 'United Kingdom',
    'Jill Haworth': 'United Kingdom',
    'Keef Hartley': 'United Kingdom',
    '与猶啓至': 'Japan',
    'Los Muertos Vivientes': 'Brazil',
    'Leon Revol': 'France',
    'Locos': 'Canada',
    'Meiso': 'Japan',
    'Phantom 5': 'Germany',
    'Pocket Chestnut': 'Italy',
    'Samuel Beckett': 'France',
    'Siloah': 'Germany',
    'Stop Play Moon': 'Brazil',
    'Tone Set': 'United States',
    'Want You NOW': 'Russia',
    'Море облаков': 'Russia',
    '林曉培': 'Taiwan',
    'Bass Outlaws': 'United States',
    'Billy Thompson': 'United States',
    'Chris Cox': 'Austria',
    'Dunderhead': 'United Kingdom',
    'Herald': 'Estonia',
    'İbrahim Erkal': 'Turkey',
    'ILMARI': 'Japan',
    'Kalapács': 'Hungary',
    'Kolo Novo Movie Band': 'South Africa',
    'La Delio Valdez': 'Argentina',
    'Look Alive': 'United States',
    'Luc St. Pierre': 'Canada',
    'MC Neat': 'United Kingdom',
    'Monkeypriest': 'Spain',
    'Nick Rhodes': 'United Kingdom',
    'Nikolaj Znaider': 'Denmark',
    'Piiptsjilling': 'Netherlands',
    'Pulsation': 'Germany',
    'Ray Castoldi': 'United States',
    'Rhythm Power': 'South Korea',
    "Steady Mobb'n": 'United States',
    'This Busy Monster': 'United States',
    'Uiscedwr': 'United Kingdom',
    'Önder Focan': 'Turkey',
    'Albert Marzinotto': 'Italy',
    'Anagram': 'Denmark',
    'Anda Union': 'China',
    'Autoritär': 'Germany',
    'Baskervillain': 'Australia',
    'Casketkrusher': 'Netherlands',
    'Chico Álvarez': 'United States',
    'Choker Campbell': 'United States',
    'Cristina Soto': 'United States',
    'Daniel Ledwell': 'Canada',
    'Darkest Horizon': 'Germany',
    'Honey G': 'United Kingdom',
    'Iguana Party': 'Sweden',
    'Ivanov': 'France',
    'Kiveskives': 'Finland',
    'Los Lobotomys': 'United States',
    'Massimo Zamboni': 'Italy',
    'Midvinter': 'Sweden',
    'Order': 'Norway',
    'Pascal Babare': 'Australia',
    'Phil Everly': 'United States',
    'Raheem Jamal': 'United States',
    'Ricercar Consort': 'Belgium',
    'Sean Brosnan': 'United Kingdom',
    'Shayne Carter': 'New Zealand',
    'Skeletal': 'Finland',
    'Smoovie Baby': 'United States',
    'Solhal': 'France',
    'Soulshine': 'United States',
    'Standarte': 'Italy',
    'Sunny & the Sunglows': 'United States',
    'The Door and the Window': 'United Kingdom',
    'The Hound Dogs': 'Germany',
    'The Smoking Hearts': 'United Kingdom',
    'U.P. Wilson': 'United States',
    'Юрий Гальцев': 'Russia',
    '三宅一徳': 'Japan',
    'Adyta': 'Georgia',
    'Björnskov': 'Denmark',
    'Бямбасүрэнгийн Шарав': 'Mongolia',
    'Carl Jackson': 'United States',
    'Chalice and Blade': 'Canada',
    'Davide Carbone': 'Australia',
    'Dilema': 'Spain',
    'Eldbjørg Raknes': 'Norway',
    'Gilyto': 'Cape Verde',
    'Gordon Withers': 'United States',
    'Grover Mitchell': 'United States',
    'Hakkı Bulut': 'Turkey',
    'Harry Rowohlt': 'Germany',
    'I-Sound': 'United Kingdom',
    'Jenna Reid': 'United Kingdom',
    'Jim Pavloff': 'Ukraine',
    'Jim-X': 'France',
    'Kensington Road': 'Germany',
    'Kimi Djabaté': 'Portugal',
    'Le Groupe Obscur': 'France',
    'Life Sentence': 'United States',
    'Louis Petrucciani': 'France',
    'Masoch': 'France',
    'Merrie Amsterburg': 'United States',
     'Far-Out Fangtooth': 'United States',
    'Fuselage': 'United Kingdom',
    'Harri Raatikainen': 'Finland',
    'Heroic Doses': 'United States',
    'Hip Hop Pantsula': 'South Africa',
    'Hurricane Heart Attacks': 'Argentina',
    'John Taylor Trio': 'United Kingdom',
    'Jonathan Kaspar': 'Germany',
    'Logical Nonsense': 'United States',
    'Mathieu Ruhlmann': 'Canada',
    'Nira K': 'Sweden',
    'Rob Mills': 'Australia',
    'Safariari': 'Norway',
    'Sergio Vartolo': 'Italy',
    'SuSu': 'United States',
    'The Trend': 'United States',
    'uchuu,': 'Japan',
    'Umilenie': 'Argentina',
    'Vallorch': 'Italy',
    'Al Agami': 'Denmark',
    'Allegra': 'Italy',
    'Czeremszyna': 'Poland',
    'Dirk Bergmann': 'Germany',
    'DJ Noise': 'Switzerland',
    'Donnez': 'Sweden',
    'Ely Buendia': 'Philippines',
    'Esmé Patterson': 'United States',
    'Exit Oz': 'Romania',
    'Gesang': 'Indonesia',
    'Sir John Stainer': 'United Kingdom',
    'Just Like Rainbows': 'Belgium',
    'Kinstrife & Blood': 'Australia',
    'Lawrence Le Doux': 'Belgium',
    'Margaret Island': 'Hungary',
    'Nicolas Ferranti': 'Switzerland',
    'One Way Letter': 'United States',
    'Refraction': 'Australia',
    'The Soul Trippers': 'United States',
    'Thee Orakle': 'Portugal',
    'Uke': 'Spain',
    'Whiskey Pete': 'United States',
    'Hvøsch': 'Russia',
    'micazo': 'Japan',
    'Bertus Staigerpaip': 'Netherlands',
    'Betty Blue': 'United States',
    'Black Friday': 'Italy',
    'Christine Cooper': 'United Kingdom',
    'DJ Fatte': 'Czech Republic',
    'Day Of Rising': 'Spain',
    'Emilie Brandt': 'United States',
    'Ewa Roos': 'Sweden',
    'Frigidaire Tango': 'Italy',
    'Giovanni Benedetto Platti': 'Italy',
    'Iron Fist': 'France',
    'Joe Crookston': 'United States',
    'Joe Morello': 'United States',
    'John Baumann': 'United States',
    'John Dimas': 'Germany',
    'Josh Gilligan': 'United States',
    'Julith Krishun': 'Germany',
    'Justicious': 'Lithuania',
    'Karen Akers': 'United States',
    'Kay Johannsen': 'Germany',
    'Legions': 'United States',
    'Marienbad': 'Germany',
    "Morgan O'Kane": 'United States',
    'Oscar Moore': 'United States',
    'Paul Austin Kelly': 'United States',
    'Real Fur': 'United Kingdom',
    'Robert Ramsey': 'United Kingdom',
    'Santoros': 'United States',
    'Saikozaurus': 'Ukraine',
    'Salamander Crossing': 'United States',
    'Ted Daffan': 'United States',
    'The Odious': 'United States',
    'The Plea': 'Ireland',
    'The Thumbs': 'United States',
    'AiA': 'Finland',
    '❀ Foliage ❀': 'United States',
    'Arian 1': 'Peru',
    'Bill Deraime': 'France',
    'Chiara Iezzi': 'Italy',
    'DJ Electric': 'Russia',
    'Disciples of Mockery': 'United States',
    'Freddy Weller': 'United States',
    'Grave Pool': 'United States',
    'Ian McLagan': 'United Kingdom',
    'Johan Asherton': 'France',
    'Lisa Brescia': 'United States',
    'MIGHT': 'United Kingdom',
    'Novo Tom': 'Brazil',
    'Ore': 'Turkey',
    'Pierre in the Air': 'Australia',
    'Plethyn': 'United Kingdom',
    'Psycho Baba': 'Japan',
    'Rejecta': 'Netherlands',
    'River Town Saints': 'Canada',
    'Scheisse Minnelli': 'Germany',
    'xac': 'Japan',
    'fOUL': 'Japan',
    'STM': 'Estonia',
    'Александр Добрынин': 'Soviet Union',
    'Михаил Светин': 'Soviet Union',
    '原由実': 'Japan',
    'Aubergine Machine': 'United States',
    'Bäsk': 'Sweden',
    'Cemetary 1213': 'Sweden',
    'Diane Keaton': 'United States',
    'Dubtonic Kru': 'Jamaica',
    'Ex-plosion': 'Russia',
    'Hyleen': 'France',
    'Hùng Cường': 'Vietnam',
    'Index AI': 'United States',
    'Jacques Bon': 'France',
    'Joel Kolltveit': 'Norway',
    'Karin Kent': 'Netherlands',
    'Kitchen': 'Switzerland',
    'Liuba María Hevia': 'Cuba',
    'MO*HO*BISH*O*PI': 'United Kingdom',
    "Max Beesley's High Vibes": 'United Kingdom',
    'Moon Gangs': 'United Kingdom',
    'Nina Attal': 'France',
    'Pat Bowie': 'United States',
    'People On Vacation': 'United States',
    'Pete Adams': 'United Kingdom',
    'Primo & Squarta': 'Italy',
    'Sons of Freedom': 'Canada',
    'The Blue Men': 'United Kingdom',
    'The Diamondheads': 'United States',
    'X-in June': 'Germany',
    'Emergent': 'United States',
    'フランシュシュ': 'Japan',
    '伊東えり': 'Japan',
    'Above All': 'United States',
    'Antonio De Angelis': 'United Kingdom',
    'Bill Emerson': 'United States',
    'Breezin Evaflowah': 'Russia',
    'C.P.O.': 'United States',
    'Chicago Symphony Chorus': 'United States',
    'D. Charles Speer': 'United States',
    'Dementia ad Vitam': 'France',
    'Dindin': 'France',
    'Goro': 'Czech Republic',
    'Guy Carawan': 'United States',
    'HORNSS': 'United States',
    'Human Serpent': 'Greece',
    'Impact Fuze': 'Russia',
    'Jersey Budd': 'United Kingdom',
    'Johnny Wyatt': 'United States',
    'Karl Amadeus Hartmann': 'Germany',
    'Linda Hoyle': 'United Kingdom',
    'Dr. Louie Giglio': 'United States',
    'M-pire of Evil': 'United Kingdom',
    'NadimaČ': 'Serbia',
    'Nick Jonah Davis': 'United Kingdom',
    'Oh, Napoleon': 'Germany',
    'Osvaldo Montes': 'Argentina',
    'Portanexus': 'United Kingdom',
    'Prison of Mirrors': 'United States',
    'Raindrop': 'South Korea',
    'Rasheed Chappell': 'United States',
    'Renn Woods': 'United States',
    'The Quotes': 'Netherlands',
    'Thralldom': 'United States',
    'Vorkuta': 'Hungary',
    '박화요비': 'South Korea',
    'Bathaus': 'United States',
    'Big Hud': 'United States',
    "Bk'": 'Brazil',
    'Cometz': 'Sweden',
    'DJ Limited': 'United Kingdom',
    'Daru Jones': 'United States',
    'Extinction A.D.': 'United States',
    'Feto in Fetus': 'Poland',
    'G Force': 'United Kingdom',
    '菊池ひみこ': 'Japan',
    'Hiphop Tamizha': 'India',
    'Hungarian Quartet': 'Hungary',
    'Johnny Massacre': 'Japan',
    'Justin Tranter': 'United States',
    'Koroded': 'Germany',
    'Kåre Nordstoga': 'Norway',
    'Les Vikings': 'Haiti',
    'Outcry': 'Spain',
    'Pelvis': 'United Kingdom',
    'Pussy Wizard': 'United States',
    'Pyramids of Mu': 'United Kingdom',
    'Pääkköset': 'Finland',
    'Rachel Barton Pine': 'United States',
    'Schnuckenack Reinhardt': 'Germany',
    'Shadow System': 'United Kingdom',
    'Sonora Casino': 'Peru',
    'The Fizzbombs': 'United Kingdom',
    'The National Splits': 'United States',
    'Tom Fletcher': 'United Kingdom',
    'Use to Abuse': 'Germany',
    'Vonder & Bloom': 'Netherlands',
    'Zip': 'France',
    'Zool': 'France',
    'Zé Cafofinho e Suas Correntes': 'Brazil',
    'Aiko Nakasone': 'United States',
    'Aleksander Maliszewski': 'Poland',
    'André Messager': 'France',
    'Beatrice Rana': 'Italy',
    'Blue J': 'Canada',
    'Casketnail': 'Germany',
    'Double Yellow': 'United Kingdom',
    'Falcko': 'France',
    'Footwork': 'United States',
    'Greg Kurstin': 'United States',
    'Harsh Reality': 'United Kingdom',
    'Intra Spelaeum': 'Russia',
    'Lirr': 'Germany',
    'Late Bloomers': 'Denmark',
    'Lesbian Mouseclicks': 'Netherlands',
    'Letter 7': 'United States',
    'Little Bob Story': 'France',
    'Loni Rose': 'United States',
    'MC ADE': 'United States',
    'Mambo Loco': 'United States',
    'Maps for Travelers': 'United States',
    'Metin Özülkü': 'Turkey',
    'Muleskinner': 'United States',
    'Raveena Aurora': 'United States',
    'Ripcordz': 'Canada',
    'Royal Marines': 'United Kingdom',
    'Rômulo Fróes': 'Brazil',
    'Schulz': 'Canada',
    'Sergio Salvatore': 'United States',
    'Spectral Mortuary': 'Denmark',
    'Sproatly Smith': 'United Kingdom',
    'Superuva': 'Argentina',
    'Tubelight': 'Belgium',
    'Van Delta': 'Germany',
    'Viggo Sandvik': 'Norway',
    'Voodoo Band': 'Russia',
    'Wittyboy': 'United Kingdom',
    'Zero Frequency': 'Estonia',
    'Zones': 'United Kingdom',
    'Asstrio': 'Spain',
    'Bill Bourne': 'Canada',
    'Boon': 'Austria',
    'boon': 'United States',
    "Broughton's Rules": 'United States',
    'Da Mob': 'United States',
    'Danny Kortchmar': 'United States',
    'Dieter Hallervorden': 'Germany',
    'East End Dubs': 'United Kingdom',
    'Fabian Almazan': 'United States',
    'Fabio Cobelli': 'Italy',
    'Galerie Schallschutz': 'Germany',
    'Gordon Jenkins & His Orchestra': 'United States',
    'Hallo': 'Japan',
    'Highness': 'United States',
    'HyperJuice': 'Japan',
    'Jesse Lee Turner': 'United States',
    'KMM団': 'Japan',
    'Karybdis': 'United Kingdom',
    'Know V.A.': 'Netherlands',
    'LA-X': 'Mexico',
    'Leah Rosier': 'Netherlands',
    'Leah Siegel': 'United States',
    'Nakka': 'Russia',
    'Nancy Kerr': 'United Kingdom',
    'Ordeal': 'Germany',
    'Provenzano DJ': 'Italy',
    'Sferi': 'Macedonia',
    'Sneaky Pinks': 'United States',
    'Snotkop': 'South Africa',
    'Starlings': 'United Kingdom',
    'Stressface': 'United States',
    'Vic Dickenson': 'United States',
    'Yura Yura': 'France',
    'iconAclass': 'United States',
    '高岡亜衣': 'Japan',
    'Alan Clark': 'United Kingdom',
    'Arizon': 'Australia',
    'Black Egg': 'Germany',
    'Black Kronstadt': 'Canada',
    'Detty Kurnia': 'Indonesia',
    'Doyle & The Fourfathers': 'United Kingdom',
    'Frank Ashton': 'Netherlands',
    'Gert Timmerman': 'Netherlands',
    'Grand Prix’s': 'United States',
    'HOUJIROU': 'Japan',
    'Heirlooms of August': 'Argentina',
    'Hudson Alexander': 'Canada',
    'IC Falkenberg': 'Germany',
    'John Harbison': 'United States',
    'Jonathan Eng': 'Sweden',
    'Juventus': 'Czechoslovakia',
    'Kerstin Blodig': 'Germany',
    'Makeba': 'United States',
    'NGT48': 'Japan',
    'Nils Grevillius': 'Sweden',
    'Papa Reu': 'United States',
    'Raquel Rastenni': 'Denmark',
    'Sebastian Riedel': 'Poland',
    'Seychal-Mills': 'Switzerland',
    'Shoplifter': 'Japan',
    'Silberbach': 'Germany',
    'Solpara': 'United States',
    'Sonata Nocturna': 'Spain',
    'The Gremlins': 'New Zealand',
    'Tanchiky': 'Japan',
    'Tropiezo': 'United States',
    'İlhan Mimaroğlu': 'Turkey',
    'Море!': 'Russia',
    '榊原郁恵': 'Japan',
    'Action Swingers': 'United States',
    'Anne Waldman': 'United States',
    'Bad 4 Good': 'United States',
    'Beachniks': 'United States',
    'Carcrashlander': 'United States',
    'Chet Baker Sextet': 'United States',
    'Cindy Mizelle': 'United States',
    'Cold Therapy': 'Poland',
    'Downstairs Left': 'Germany',
    'Frank Howard & The Commanders': 'United States',
    'Gary Valentine': 'United States',
    'Hannah Telle': 'United States',
    'Herb Ohta': 'United States',
    "Immigrant's Bossa Band": 'Japan',
    'Jackson Firebird': 'Australia',
    'Kali Bahlu': 'United States',
    'サエキけんぞう': 'Japan',
    'Knut Nystedt': 'Norway',
    'Leonard Weir': 'United Kingdom',
    'Mick Mars': 'United States',
    'Off the Cross': 'Belgium',
    'Rise of Avernus': 'Australia',
    'Shizoe': 'Germany',
    'Skeptical Minds': 'Belgium',
    'Sérgio Dias': 'Brazil',
    'Testsieger': 'Germany',
    'The Dregs': 'United Kingdom',
    'The McTells': 'United Kingdom',
    "Tony O'Hora": 'United Kingdom',
    'Tourettes': 'New Zealand',
    'coffin princess': 'Japan',
    'Атом-76': 'Russia',
    'イヤホンズ': 'Japan',
    '平川地一丁目': 'Japan',
    'A.R.T Wilson': 'Australia',
    'Beatropolis': 'United States',
    'Bingo Trappers': 'Netherlands',
    'Chen Reiss': 'Israel',
    'Clitoridus Invaginatus': 'Italy',
    'Derek Roddy': 'United States',
    'Dezmond Dez': 'Switzerland',
    'Dixie Peach': 'United Kingdom',
    'Eldar Vågan': 'Norway',
    'Etat Brut': 'Belgium',
    'Euglossine': 'United States',
    'Glen Scott': 'United Kingdom',
    'Joe Burke': 'Ireland',
    'Kenelis': 'United Kingdom',
    'Kreptkrept': 'United States',
    'Lawrence Walker': 'United States',
    'Lisa Hammer': 'United States',
    'Mamoru Fujieda': 'Japan',
    'Mehrad Hidden': 'Iran',
    "Mother Tucker's Yellow Duck": 'United States',
    'Neoandertals': 'Estonia',
    'Note to Self: Don’t Die!': 'United Kingdom',
    'Overdog': 'Germany',
    'Panama Rayo': 'Finland',
    'Plutonium': 'Sweden',
    'Ralf Wengenmayr': 'Germany',
    'Reign of Terror': 'United States',
    'Robert A. Heinlein': 'United States',
    'Robert Balzar Trio': 'Czech Republic',
    'Satan on Fire': 'United States',
    'سعاد عبد ال': 'Kuwait',
    'Teddy Tahu Rhodes': 'New Zealand',
    'The Cesta All Stars': 'United States',
    'The Hogs': 'United States',
    'Trigger Effect': 'Canada',
    'The Two Tears': 'United States',
    'Valya Balkanska': 'Bulgaria',
    'Vromm': 'United Kingdom',
    'Walter Marchetti': 'Italy',
    'Aislin': 'United Kingdom',
    'Annalisa Minetti': 'Italy',
    'Art Inc.': 'Netherlands',
    'Band of Oz': 'United States',
    'Billy Storm': 'United States',
    'Bordge': 'Russia',
    'Carl Bonafede': 'United States',
    'Chris Rosser': 'United States',
    'Cincinnati Wind Symphony': 'United States',
    'Curtis Hobock': 'United States',
    'David McComb': 'Australia',
    'Delirion': 'Spain',
    'Europe 1': 'France',
    'Fresh Color': 'Switzerland',
    'Funeral Goat': 'Netherlands',
    'Grismannen': 'Sweden',
    'Joan Isaac': 'Spain',
    'Lax Alex Contrax': 'Germany',
    'Maurice El Médioni': 'France',
    'Neaux': 'United States',
    'Nous': 'Netherlands',
    'Paris XY': 'United Kingdom',
    'Petit Mal': 'United States',
    'Ray de La Paz': 'United States',
    'Sammy Barbot': 'France',
    'Steampacket': 'Sweden',
    'Steve Wright': 'United States',
    'Subtract': 'New Zealand',
    'The Undertaker': 'United States',
    'Thomas Eje': 'Denmark',
    'Vincent Black Shadow': 'Finland',
    'Yellowstone & Voice': 'United Kingdom',
    'Minimall': 'United States',
    'Ákos Rózmann': 'Sweden',
    '前野曜子': 'Japan',
    'Adrien': 'France',
    'Born Again': 'France',
    'Brij Bhushan Kabra': 'India',
    'Christina Dahl': 'United States',
    'Cowboys on Dope': 'Germany',
    'David Brown': 'United States',
    'Eduardo Capetillo': 'Mexico',
    'Eliza Lynn': 'United States',
    'Funeral Forest': 'France',
    'Harri Wessman': 'Finland',
    'Hundred Visions': 'United States',
    'Hypnoteck': 'Belgium',
    'Kuve': 'Spain',
    'Mahaleo': 'Madagascar',
    'Mammoth Indigo': 'United States',
    'Milwaukee Symphony Orchestra': 'United States',
    'Paul Schoenfield': 'United States',
    'Pestilentia': 'Belarus',
    'Ramana Gogula': 'India',
    'Rita Connolly': 'Ireland',
    'Saratan': 'Poland',
    'The Stay at Home Joneses': 'United States',
    'อพาร์ตเมนต์คุณป้า': 'Thailand',
    '黃大煒': 'Taiwan',
    "2 Body's": 'Belgium',
    'Big Balls & the Great White Idiot': 'Germany',
    'Borrowed Time': 'United Kingdom',
    'DJ Cable': 'United Kingdom',
    'Die Quietschboys': 'Germany',
    "Elfa's Singers": 'Indonesia',
    'I Do Not Love': 'United States',
    'Ken Cook': 'United States',
    'Kusari Gama Kill': 'Denmark',
    'LOAFERS': 'United States',
    'La Résistance': 'Canada',
    'Mara Lima': 'Brazil',
    'Marco Uccellini': 'Italy',
    'Matt Zanardo': 'Canada',
    'Mr. Bean': 'United Kingdom',
    'Phunktastike': 'Argentina',
    'Pushaz': 'Lithuania',
    'Reverend Elvis': 'Germany',
    'Roger Willemsen': 'Germany',
    'Rubén Albarrán': 'Mexico',
    'Shane Gamble': 'United States',
    'Skontra': 'Spain',
    'Slaughtered Priest': 'Greece',
    'TerraTeCH': 'Portugal',
    'The Baja Marimba Band': 'United States',
    'Tony Colombo': 'Italy',
    'Yolanda Selini': 'Norway',
    'Ahmad Alaadeen': 'United States',
    'Altercation': 'United States',
    'Blotter': 'Austria',
    'Blunderbuss': 'United States',
    'Cecelia Ahern': 'Ireland',
    'Color Source': 'United States',
    'Darkside of the Force': 'Norway',
    'Diamond Field': 'United States',
    'Die Gefahr': 'Germany',
    'Dú Maroc': 'Germany',
    'Greg & Steve': 'United States',
    'HVNS': 'Estonia',
    'Ivana Selakov': 'Serbia',
    'Jade MacRae': 'Australia',
    'Johnnie Bassett': 'United States',
    'Marielle Labèque': 'France',
    'Mikser': 'Poland',
    'Mussoumano': 'Brazil',
    'Omar Kent Dykes': 'United States',
    'Popkan': 'United States',
    'Raza Obrera': 'Mexico',
    'Razorwire': 'United States',
    'Rena Rolska': 'Poland',
    'Rodolfo Mederos': 'Argentina',
    'Rosita Serrano': 'Chile',
    'SLNT': 'Argentina',
    'SS-18': 'Russia',
    'Scott Storch': 'United States',
    'Serpents Lair': 'Denmark',
    'Servovalve': 'France',
    'Setrak Sarkissian': 'Lebanon',
    'Tinneri': 'Finland',
    'Trent Gardner': 'United States',
    'vividblaze': 'Japan',
    '21 Love Hotel': 'France',
    '4th Sign of the Apocalypse': 'United States',
    'Charly Hübner': 'Germany',
    'Consolers': 'Germany',
    'Cuebism': 'Germany',
    'Danyka Nadeau': 'Canada',
    'Deep Six': 'United States',
    'Elviira & Rake': 'Finland',
    'Francisco de la Torre': 'Spain',
    'Gomez & Dubois': 'France',
    'Ham Den Lange': 'Denmark',
    'Hoodoo': 'Germany',
    'Janne': 'Finland',
    'Jeremy Storch': 'United States',
    'John W. Summers': 'United States',
    'Keith Bryant': 'United States',
    'Kimberly Nichole': 'United States',
    'Monument of Urns': 'United States',
    'Nick Curran': 'United States',
    'Silver Bullets': 'Italy',
    'Solitair': 'Canada',
    'Surji': 'Russia',
    'Synagi': 'Japan',
    'The Beatnix': 'Australia',
    'The Boy Bathing': 'United States',
    'The Incredible Staggers': 'Austria',
    '渚ゆう子': 'Japan',
    'Aghast!': 'United Kingdom',
    'Alexandre de Faria': 'Brazil',
    'Alienated': 'United Kingdom',
    'Ankaralı Turgut': 'Turkey',
    'Apolas Lermi': 'Turkey',
    'Athanor': 'France',
    'Chalice of Blood': 'Sweden',
    'Dave Glasser': 'United States',
    'Escolania de Montserrat': 'Spain',
    'FFT': 'United Kingdom',
    'Inferious': 'United States',
    'Kigo': 'Australia',
    'Larry Johnson': 'United States',
    'Little Bushman': 'New Zealand',
    'Mahavatar': 'United States',
    'Mario Pavone': 'United States',
    'Mentalease': 'United States',
    'Mitchell Sigman': 'United States',
    'Munro': 'South Africa',
    'My Favourite Nemesis': 'Finland',
    'New Fries': 'Canada',
    'Panzar': 'Sweden',
    'Pearl Future': 'United States',
    'Peces Raros': 'Argentina',
    'Radboud Mens': 'Netherlands',
    'Reinmar Henschke': 'Germany',
    'Sir Henry Wood': 'United Kingdom',
    'Spider and the Webs': 'United States',
    'The Darlingtons': 'United Kingdom',
    'The Paupers': 'Canada',
    'Zevious': 'United States',
    '山下毅雄': 'Japan',
    '田中雅之': 'Japan',
    'ADAL': 'United Kingdom',
    'Aranza': 'Mexico',
    'Celloman': 'United Kingdom',
    "Charlotte O'Connor": 'United States',
    'Cthulhu Rise': 'Ukraine',
    'Dark Diamonds': 'Germany',
    'David Reeves': 'Canada',
    'Deutscher Kaiser': 'Germany',
    'eNoz': 'France',
    'Five! Fast!! Hits!!!': 'Germany',
    'Jacqui Abbott': 'United Kingdom',
    'John McSherry': 'United Kingdom',
    'kleinmeister': 'Germany',
    'Loretta Who': 'Austria',
    'Mayumi': 'Japan',
    'Old Kerry McKee': 'Sweden',
    'PSYQUI': 'Japan',
    'Panda Teeth': 'United States',
    'Pornografia': 'Poland',
    'Progressiver': 'Ukraine',
    'Shiny Two Shiny': 'United Kingdom',
    'Shira Small': 'United States',
    'Shirati Jazz': 'Kenya',
    'T.x.T': 'Germany',
    'The Miracle': 'Italy',
    'The Nematoads': 'United States',
    'The New Yorkers': 'United States',
    'Die Trenkwalder': 'Austria',
    'Unnatural Axe': 'United States',
    'Victor Dimisich Band': 'New Zealand',
    '柿島伸次': 'Japan',
    '盧凱彤': 'Canada',
    'Alborotador Gomasio': 'Spain',
    'Bloquera': 'United States',
    'Carrera': 'Netherlands',
    'Celkilt': 'France',
    'Deelicious': 'United Kingdom',
    'Fire Next Time': 'United Kingdom',
    'Gros Mo': 'France',
    'Human Waste': 'United States',
    'Jajo': 'Iran',
    'José Menese': 'Spain',
    'Madi Davis': 'United States',
    'Miles Graham': 'Ireland',
    'Nando Cordel': 'Brazil',
    'Naomi Hates Humans': 'United Kingdom',
    'New Today': 'United States',
    'Nicolas Vallet': 'Netherlands',
    'Odhinn': 'Sweden',
    'Onanizer': 'Czech Republic',
    'Regn': 'Norway',
    'Schattenspiel': 'Germany',
    'Shauna Burns': 'United States',
    'Sig Transit Gloria': 'United States',
    'Suonho': 'Italy',
    'Ted Daigle': 'Canada',
    'The Grand Skeem': 'United States',
    'The Teddy Boys': 'United States',
    'Vänsternäven': 'Sweden',
    'Zorba & The Greeks': 'United States',
    'Dirkschneider': 'Germany',
    'totsumal': 'Japan',
    'Zetazen': 'Spain',
    'КариZма': 'Bulgaria',
    'Привидение с мотором': 'Russia',
    '川辺ヒロシ': 'Japan',
    '長澤知之': 'Japan',
    '(립서비스) Lip Service': 'South Korea',
    '아홉소녀들': 'South Korea',
    'Acolyte': 'Greece',
    'Aerophonics': 'Russia',
    'AlterRed': 'United Kingdom',
    'Antero Manninen': 'Finland',
    'Antti Rannisto': 'Finland',
    'Asylum on The Hill': 'United States',
    'Bowsar': 'Austria',
    'Dead Silence': 'Russia',
    "Dusty 45's": 'United States',
    'Edwina De Pooter': 'Germany',
    'F.E.V.E.R.': 'Portugal',
    'Heinrich Heine': 'Germany',
    'Inespe': 'Poland',
    'Kelly Richey': 'United States',
    'Korium': 'Slovakia',
    'Lewis Boardman': 'United Kingdom',
    'Marlon Hoffstadt': 'Germany',
    'Młynarski plays Młynarski': 'Poland',
    'Nikki Gregoroff': 'United States',
    'Pete Pascoe': 'Australia',
    'relapxych.0': 'Sweden',
    'Sally Eaton': 'United States',
    'Salomé Anjarí': 'Chile',
    'Six Going on Seven': 'United States',
    'Sleepy Eyes Nelson': 'United Kingdom',
    'Sole Remedy': 'Finland',
    'Somrak': 'Slovenia',
    'Surrealizt': 'Australia',
    'THE BALD HEADS': 'Japan',
    'The Judas Factor': 'United States',
    'Yaco Monti': 'Argentina',
    'Zond': 'Australia',
    'Isle of You': 'Sweden',
    '三村京子': 'Japan',
    '福原遥': 'Japan',
    '遠藤ミチロウ': 'Japan',
    'Accordi Disaccordi': 'Italy',
    'ADAMA': 'Israel',
    'Adama': 'United States',
    'Bernarda Fink': 'Austria',
    'Byron Westbrook': 'United States',
    'Coin': 'Australia',
    'Charlie Barnett': 'United States',
    'Cláudio Zoli': 'Brazil',
    'Coki & The Killer Burritos': 'Argentina',
    'Crying Steel': 'Italy',
    'KV5': 'United Kingdom',
    'Le Phonographe': 'Russia',
    'Left In Torment': 'France',
    'Master Joe & O.G. Black': 'United States',
    'Michał Kleofas Ogiński': 'Poland',
    'Miura': 'Italy',
    'Mr. Brightside': 'Ukraine',
    'Old One': 'United States',
    'positive MAD-crew': 'Japan',
    'Red Sky': 'United States',
    'Stephan Peixoto': 'Brazil',
    'The Mare': 'Sweden',
    'Vontel': 'United States',
    'Wojciech Paszkowski': 'Poland',
    '김재양': 'South Korea',
    'Alderaan': 'France',
    'Alessandro Fiori': 'Italy',
    'Andreas Fahnert': 'Germany',
    'Anton Belov': 'Russia',
    'ARKTKT': 'United States',
    'Autumn Verses': 'Finland',
    'Bức Tường': 'Vietnam',
    'DSC': 'Morocco',
    'Daryl Runswick': 'United Kingdom',
    'Dino Joubert': 'Germany',
    'François Tétaz': 'Australia',
    'Giorgio Mainerio': 'Italy',
    'Helen Keller': 'United States',
    'Jeremy Weinglass': 'United States',
    'Jerry Dammers': 'United Kingdom',
    'John Weird': 'Ukraine',
    'Johnny Robinson': 'United Kingdom',
    'Layment': 'Germany',
    'Limacon': 'United States',
    'Mo’Hawk': 'Netherlands',
    'Mestre Marçal': 'Brazil',
    'Sheryo': 'France',
    'Soul Camp': 'Japan',
    'Stig Kreutzfeldt': 'Denmark',
    'The Alligators': 'United States',
    'The Elves': 'United States',
    'Tucker Smith': 'United States',
    'Your Mother': 'United States',
    'Adolf and the Piss Artists': 'United States',
    'Betty Missiego': 'Peru',
    'Big Mato': 'United States',
    'David Sabella': 'United States',
    'Dance Macabre': 'Netherlands',
    'Dušan Bogdanović': 'United States',
    'Elif Kaya': 'Turkey',
    'Emazet': 'Poland',
    'Eric Ericson': 'Sweden',
    'For Teens': 'Poland',
    'Forefathers': 'United States',
    'Ghost Quartet': 'United States',
    'Interflow': 'United Kingdom',
    'Jan P. Muchow': 'Czech Republic',
    'Konzertvereinigung Wiener Staatsopernchor': 'Austria',
    'LMNOP': 'United States',
    'Lepistö & Lehti': 'Finland',
    'Les Quatre Barbus': 'France',
    'Marília Medalha': 'Brazil',
    'Prod': 'Australia',
    'Richie Gee': 'Spain',
    'Street Pharmacy': 'Canada',
    'Sunken Seas': 'New Zealand',
    'The Dead Next Door': 'Sweden',
    'The Defibulators': 'United States',
    'The Staccatos': 'United Kingdom',
    'The Undergods': 'United States',
    'United Travel Service': 'United States',
    '雅夢': 'Japan',
    'Alex Moran': 'United Kingdom',
    'Aphletik': 'United Kingdom',
    'Audio Empire': 'New Zealand',
    'Ave Astra': 'Turkey',
    'Brooke Allison': 'United States',
    'Comacozer': 'Australia',
    'Capitán Sunrise': 'Spain',
    'Dale Crover': 'United States',
    'Dan Jones': 'United Kingdom',
    'De Beren Gieren': 'Belgium',
    'Devoid Of Grace': 'Russia',
    'Dronebixie': 'Denmark',
    'Edwin Moses': 'Spain',
    'Glue Kids': 'Spain',
    'Khost': 'United Kingdom',
    'Lawrence Ashmore': 'United Kingdom',
    'Leslie Sarony': 'United Kingdom',
    'Limited': 'United States',
    'My Hair is Bad': 'Japan',
    "O'Neill": 'United States',
    'Paul Pfau': 'United States',
    'Prima Choir': 'Canada',
    'Rockfolket': 'Sweden',
    'STF': 'Germany',
    "Stephen Brodsky's Octave Museum": 'United States',
    'SULO': 'Australia',
    'Sulo': 'Australia',
    'Swanox': 'United States',
    'Tears of Othila': 'Italy',
    'Tester Gier': 'Poland',
    'The Chicks': 'New Zealand',
    'The Street Sliders': 'Japan',
    'Bobbie Smith': 'United States',
    'Alternativ Quartet': 'Romania',
    'Anna O': 'Australia',
    'Ben Godwin': 'United Kingdom',
    'Black Furies': 'United States',
    'Boot Party': 'United States',
    'Dead Ringers': 'United Kingdom',
    'Domino Theory': 'United States',
    'Dr. FeelX': 'Italy',
    'Ellen Doty': 'Canada',
    'Failed Flowers': 'United States',
    'Gardna': 'United Kingdom',
    'Hurdles': 'United Kingdom',
    'Joey Jordison': 'United States',
    'Klooch': 'Canada',
    'Liverpool Five': 'United Kingdom',
    'Louise McCord': 'United States',
    'Melted': 'United States',
    'Mysterya': 'Ukraine',
    'One Eye Open': 'United States',
    'Os Dentes': 'Brazil',
    'Radikal Satan': 'France',
    'Ron Affif': 'United States',
    'Stem': 'Estonia',
    'The Rites': 'United States',
    'Droogz Brigade': 'France',
    '平野幸村': 'Japan',
    '福田沙紀': 'Japan',
    'Absvrdist': 'United States',
    'Andy Tielman': 'Netherlands',
    'Beat Syndrome': 'Canada',
    'Bjarne Liller': 'Denmark',
    'Brix Smith': 'United Kingdom',
    'César Costa': 'Mexico',
    'DJ Chrome': 'France',
    'DJ Ron': 'United Kingdom',
    'Darchon': 'Greece',
    'Dastan Ensemble': 'Iran',
    'Doug Anderson': 'United States',
    'E-De-Cologne': 'Germany',
    'Findlay Napier': 'United Kingdom',
    'Flembaz': 'Portugal',
    'Jesse Osborne-Lanthier': 'Germany',
    'Johnny Bell': 'United States',
    'Joseph Banowetz': 'United States',
    'Karen Mantler': 'United States',
    'Khleo Thomas': 'United States',
    'Leather Corduroys': 'United States',
    'Likes Lions': 'United Kingdom',
    'Loqate': 'United Kingdom',
    'Madhushree': 'India',
    'Metalmorphose': 'Brazil',
    'Michel Elias': 'France',
    'Mr. Lex': 'Germany',
    'Nuns': 'United States',
    'Night Owls': 'United Kingdom',
    'Pacific Horizons': 'United States',
    'Pavel Callta': 'Czech Republic',
    'Pino Scotto': 'Italy',
    'Ronny Eriksson': 'Sweden',
    'Sarah Dash': 'United States',
    'Sbeast': 'United Kingdom',
    'Sean Morey': 'United States',
    'Sikumiut': 'Canada',
    'Soroush': 'Iran',
    'Superets': 'France',
    'Tarrentella': 'United Kingdom',
    'Ted Hughes': 'United Kingdom',
    'Thesis Sahib': 'Canada',
    'Zoë Avril': 'France',
    'HMGNC': 'Indonesia',
    'Александр Пономарев': 'Russia',
    'Арктика': 'Ukraine',
    'Армен Григорян': 'Russia',
    'ハニー・ナイツ': 'Japan',
    '山本正之': 'Japan',
    'Adam Wakeman': 'United Kingdom',
    'Aïcha Bint Chighaly': 'Mauritania',
    'Blindagem': 'Brazil',
    'Brainfever': 'Germany',
    'Bret Autrey': 'United States',
    'Cabaret Contemporain': 'France',
    'Dina Maccabee': 'United States',
    'Elifantree': 'Finland',
    'Elliot Adamson': 'United Kingdom',
    'Interpreti Veneziani': 'Italy',
    'Ishe': 'United States',
    'Jon Ronson': 'United Kingdom',
    'Jouni Aslak': 'Finland',
    'Katie Keller': 'Denmark',
    'Keston & Westdal': 'United Kingdom',
    'Less du Neuf': 'France',
    'Melgroove': 'France',
    'OG Eastbull': 'Italy',
    'Pitbull Terrorist': 'Finland',
    'SPAWTS': 'New Zealand',
    'Steve Lee': 'Switzerland',
    'The Fat Lady Sings': 'Ireland',
    'The Killingtons': 'United States',
    'The Out': 'United Kingdom',
    'The Pavers': 'United States',
    'The Peep Show': 'United Kingdom',
    'Thee Cormans': 'United States',
    'Traz Damji': 'Canada',
    'Vera Cruz': 'France',
    'Whiptongue': 'Brazil',
    'キエるマキュウ': 'Japan',
    '21st Century Aura': 'United Kingdom',
    'Andrew Daly': 'United States',
    'Byproduct': 'Finland',
    'Citizen Helene': 'United Kingdom',
    'Coboy Junior': 'Indonesia',
    'David Saw': 'United Kingdom',
    'Diana Yukawa': 'United Kingdom',
    'Dorina': 'Brazil',
    'Doug Wood': 'United States',
    'Earthmass': 'United Kingdom',
    'Enzo Elia': 'Italy',
    'Fluchtpunkt Terror': 'Germany',
    'Forgotten Horror': 'Finland',
    'Instruments of Science & Technology': 'United States',
    'Joan Diener': 'United States',
    'Joe Magnarelli': 'United States',
    'KadaSarva': 'Ukraine',
    'Lee Brown': 'United States',
    'Los Hermanos Rigual': 'Mexico',
    'Lou Quinse': 'Italy',
    'G.R.E.S. Estação Primeira De Mangueira': 'Brazil',
    'Margie Hendrix': 'United States',
    'My Inner Burning': 'Germany',
    'Pedro de Escobar': 'Portugal',
    'Rel': 'United States',
    'Shiko Shiko': 'France',
    'Siberian Tsars': 'Russia',
    'Systemic': 'Israel',
    'The Red Krayola with Art & Language': 'United States',
    'The Throbs': 'United Kingdom',
    'Third Mind': 'United Kingdom',
    'Toenut': 'United States',
    'Андрей Данилко': 'Ukraine',
    'Арсений Тарковский': 'Soviet Union',
    'БРАТ': 'Serbia',
    '矢野絢子': 'Japan',
    'Andreas Holm': 'Denmark',
    'Animal Youth': 'Belgium',
    'Bivouac': 'United Kingdom',
    'Café Drechsler': 'Austria',
    'Carlou D': 'Senegal',
    'Clever': 'United States',
    'J Riskit': 'Finland',
    'Jenni Viitalo': 'Finland',
    'Jonathan Coleclough': 'United Kingdom',
    'Julie & The Wrong Guys': 'Canada',
    'Kalimax': 'Sweden',
    'Kel Valhaal': 'United States',
    'Lydia Marcelle': 'United States',
    'Mary Monday': 'United States',
    'Mateu Fletxa': 'Spain',
    'Merricks': 'Germany',
    'Mike Hanapi': 'United States',
    'Morrissey & Marshall': 'United Kingdom',
    'Mr. Lewis & the Funeral 5': 'United States',
    'Na Palm': 'United States',
    'Ollie Olsen': 'Australia',
    'Paul Avion': 'United States',
    'Philippe Chrétien': 'Switzerland',
    'Rooler': 'Italy',
    'Scribes': 'United States'    
}

size = len(artists_data)

print(size)   #2891